/****************************************************************************
**
** Metadata for KHOpenAPILib generated by dumpcpp v5.12.7 using
** dumpcpp KHOPENAPI.KHOpenAPICtrl.1 -o C:\Users\kuh\go\src\github.com\ghts\ghts\kiwoom\base\kiwoom
** from the type library C:\OpenAPI\KHOpenAPI.ocx
**
****************************************************************************/

#define QAX_DUMPCPP_KHOPENAPILIB_NOINLINES
#include "kiwoom.h"

using namespace KHOpenAPILib;

struct qt_meta_stringdata_all_t {
    QByteArrayData data[162];
    char stringdata0[2028];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 25, 0),
QT_MOC_LITERAL(1, 26, 9, 0),
QT_MOC_LITERAL(2, 36, 0, 0),
QT_MOC_LITERAL(3, 37, 4, 0),
QT_MOC_LITERAL(4, 42, 6, 0),
QT_MOC_LITERAL(5, 49, 4, 0),
QT_MOC_LITERAL(6, 54, 4, 0),
QT_MOC_LITERAL(7, 59, 15, 0),
QT_MOC_LITERAL(8, 75, 4, 0),
QT_MOC_LITERAL(9, 80, 6, 0),
QT_MOC_LITERAL(10, 87, 4, 0),
QT_MOC_LITERAL(11, 92, 4, 0),
QT_MOC_LITERAL(12, 97, 11, 0),
QT_MOC_LITERAL(13, 109, 11, 0),
QT_MOC_LITERAL(14, 121, 12, 0),
QT_MOC_LITERAL(15, 134, 9, 0),
QT_MOC_LITERAL(16, 144, 10, 0),
QT_MOC_LITERAL(17, 155, 6, 0),
QT_MOC_LITERAL(18, 162, 15, 0),
QT_MOC_LITERAL(19, 178, 16, 0),
QT_MOC_LITERAL(20, 195, 9, 0),
QT_MOC_LITERAL(21, 205, 7, 0),
QT_MOC_LITERAL(22, 213, 9, 0),
QT_MOC_LITERAL(23, 223, 12, 0),
QT_MOC_LITERAL(24, 236, 8, 0),
QT_MOC_LITERAL(25, 245, 5, 0),
QT_MOC_LITERAL(26, 251, 10, 0),
QT_MOC_LITERAL(27, 262, 9, 0),
QT_MOC_LITERAL(28, 272, 10, 0),
QT_MOC_LITERAL(29, 283, 7, 0),
QT_MOC_LITERAL(30, 291, 9, 0),
QT_MOC_LITERAL(31, 301, 13, 0),
QT_MOC_LITERAL(32, 315, 18, 0),
QT_MOC_LITERAL(33, 334, 6, 0),
QT_MOC_LITERAL(34, 341, 16, 0),
QT_MOC_LITERAL(35, 358, 15, 0),
QT_MOC_LITERAL(36, 374, 17, 0),
QT_MOC_LITERAL(37, 392, 13, 0),
QT_MOC_LITERAL(38, 406, 4, 0),
QT_MOC_LITERAL(39, 411, 19, 0),
QT_MOC_LITERAL(40, 431, 7, 0),
QT_MOC_LITERAL(41, 439, 11, 0),
QT_MOC_LITERAL(42, 451, 9, 0),
QT_MOC_LITERAL(43, 461, 13, 0),
QT_MOC_LITERAL(44, 475, 11, 0),
QT_MOC_LITERAL(45, 487, 13, 0),
QT_MOC_LITERAL(46, 501, 15, 0),
QT_MOC_LITERAL(47, 517, 16, 0),
QT_MOC_LITERAL(48, 534, 20, 0),
QT_MOC_LITERAL(49, 555, 15, 0),
QT_MOC_LITERAL(50, 571, 12, 0),
QT_MOC_LITERAL(51, 584, 20, 0),
QT_MOC_LITERAL(52, 605, 13, 0),
QT_MOC_LITERAL(53, 619, 12, 0),
QT_MOC_LITERAL(54, 632, 4, 0),
QT_MOC_LITERAL(55, 637, 13, 0),
QT_MOC_LITERAL(56, 651, 17, 0),
QT_MOC_LITERAL(57, 669, 21, 0),
QT_MOC_LITERAL(58, 691, 18, 0),
QT_MOC_LITERAL(59, 710, 23, 0),
QT_MOC_LITERAL(60, 734, 24, 0),
QT_MOC_LITERAL(61, 759, 19, 0),
QT_MOC_LITERAL(62, 779, 12, 0),
QT_MOC_LITERAL(63, 792, 12, 0),
QT_MOC_LITERAL(64, 805, 13, 0),
QT_MOC_LITERAL(65, 819, 11, 0),
QT_MOC_LITERAL(66, 831, 3, 0),
QT_MOC_LITERAL(67, 835, 8, 0),
QT_MOC_LITERAL(68, 844, 23, 0),
QT_MOC_LITERAL(69, 868, 5, 0),
QT_MOC_LITERAL(70, 874, 20, 0),
QT_MOC_LITERAL(71, 895, 14, 0),
QT_MOC_LITERAL(72, 910, 10, 0),
QT_MOC_LITERAL(73, 921, 8, 0),
QT_MOC_LITERAL(74, 930, 12, 0),
QT_MOC_LITERAL(75, 943, 11, 0),
QT_MOC_LITERAL(76, 955, 16, 0),
QT_MOC_LITERAL(77, 972, 14, 0),
QT_MOC_LITERAL(78, 987, 20, 0),
QT_MOC_LITERAL(79, 1008, 21, 0),
QT_MOC_LITERAL(80, 1030, 16, 0),
QT_MOC_LITERAL(81, 1047, 14, 0),
QT_MOC_LITERAL(82, 1062, 13, 0),
QT_MOC_LITERAL(83, 1076, 13, 0),
QT_MOC_LITERAL(84, 1090, 14, 0),
QT_MOC_LITERAL(85, 1105, 24, 0),
QT_MOC_LITERAL(86, 1130, 21, 0),
QT_MOC_LITERAL(87, 1152, 17, 0),
QT_MOC_LITERAL(88, 1170, 12, 0),
QT_MOC_LITERAL(89, 1183, 17, 0),
QT_MOC_LITERAL(90, 1201, 5, 0),
QT_MOC_LITERAL(91, 1207, 13, 0),
QT_MOC_LITERAL(92, 1221, 13, 0),
QT_MOC_LITERAL(93, 1235, 6, 0),
QT_MOC_LITERAL(94, 1242, 13, 0),
QT_MOC_LITERAL(95, 1256, 8, 0),
QT_MOC_LITERAL(96, 1265, 16, 0),
QT_MOC_LITERAL(97, 1282, 7, 0),
QT_MOC_LITERAL(98, 1290, 17, 0),
QT_MOC_LITERAL(99, 1308, 9, 0),
QT_MOC_LITERAL(100, 1318, 6, 0),
QT_MOC_LITERAL(101, 1325, 10, 0),
QT_MOC_LITERAL(102, 1336, 5, 0),
QT_MOC_LITERAL(103, 1342, 4, 0),
QT_MOC_LITERAL(104, 1347, 6, 0),
QT_MOC_LITERAL(105, 1354, 7, 0),
QT_MOC_LITERAL(106, 1362, 11, 0),
QT_MOC_LITERAL(107, 1374, 15, 0),
QT_MOC_LITERAL(108, 1390, 9, 0),
QT_MOC_LITERAL(109, 1400, 9, 0),
QT_MOC_LITERAL(110, 1410, 11, 0),
QT_MOC_LITERAL(111, 1422, 8, 0),
QT_MOC_LITERAL(112, 1431, 7, 0),
QT_MOC_LITERAL(113, 1439, 6, 0),
QT_MOC_LITERAL(114, 1446, 4, 0),
QT_MOC_LITERAL(115, 1451, 6, 0),
QT_MOC_LITERAL(116, 1458, 9, 0),
QT_MOC_LITERAL(117, 1468, 11, 0),
QT_MOC_LITERAL(118, 1480, 9, 0),
QT_MOC_LITERAL(119, 1490, 13, 0),
QT_MOC_LITERAL(120, 1504, 3, 0),
QT_MOC_LITERAL(121, 1508, 6, 0),
QT_MOC_LITERAL(122, 1515, 12, 0),
QT_MOC_LITERAL(123, 1528, 10, 0),
QT_MOC_LITERAL(124, 1539, 11, 0),
QT_MOC_LITERAL(125, 1551, 11, 0),
QT_MOC_LITERAL(126, 1563, 10, 0),
QT_MOC_LITERAL(127, 1574, 10, 0),
QT_MOC_LITERAL(128, 1585, 13, 0),
QT_MOC_LITERAL(129, 1599, 10, 0),
QT_MOC_LITERAL(130, 1610, 7, 0),
QT_MOC_LITERAL(131, 1618, 23, 0),
QT_MOC_LITERAL(132, 1642, 17, 0),
QT_MOC_LITERAL(133, 1660, 17, 0),
QT_MOC_LITERAL(134, 1678, 11, 0),
QT_MOC_LITERAL(135, 1690, 11, 0),
QT_MOC_LITERAL(136, 1702, 14, 0),
QT_MOC_LITERAL(137, 1717, 8, 0),
QT_MOC_LITERAL(138, 1726, 19, 0),
QT_MOC_LITERAL(139, 1746, 6, 0),
QT_MOC_LITERAL(140, 1753, 8, 0),
QT_MOC_LITERAL(141, 1762, 8, 0),
QT_MOC_LITERAL(142, 1771, 21, 0),
QT_MOC_LITERAL(143, 1793, 4, 0),
QT_MOC_LITERAL(144, 1798, 4, 0),
QT_MOC_LITERAL(145, 1803, 23, 0),
QT_MOC_LITERAL(146, 1827, 8, 0),
QT_MOC_LITERAL(147, 1836, 12, 0),
QT_MOC_LITERAL(148, 1849, 6, 0),
QT_MOC_LITERAL(149, 1856, 22, 0),
QT_MOC_LITERAL(150, 1879, 7, 0),
QT_MOC_LITERAL(151, 1887, 17, 0),
QT_MOC_LITERAL(152, 1905, 17, 0),
QT_MOC_LITERAL(153, 1923, 9, 0),
QT_MOC_LITERAL(154, 1933, 20, 0),
QT_MOC_LITERAL(155, 1954, 5, 0),
QT_MOC_LITERAL(156, 1960, 15, 0),
QT_MOC_LITERAL(157, 1976, 9, 0),
QT_MOC_LITERAL(158, 1986, 11, 0),
QT_MOC_LITERAL(159, 1998, 10, 0),
QT_MOC_LITERAL(160, 2009, 8, 0),
QT_MOC_LITERAL(161, 2018, 8, 0)
    },
    "KHOpenAPILib::_DKHOpenAPI\0exception\0\0code\0source\0disc\0help\0propertyChanged\0"
    "name\0signal\0argc\0argv\0CommConnect\0CommGetData\0sJongmokCode\0sRealType\0sFieldName\0"
    "nIndex\0sInnerFieldName\0CommInvestRqData\0sMarketGb\0sRQName\0sScreenNo\0CommKwRqData\0"
    "sArrCode\0bNext\0nCodeCount\0nTypeFlag\0CommRqData\0sTrCode\0nPrevNext\0CommTerminate\0"
    "DisconnectRealData\0sScnNo\0GetAPIModulePath\0GetActPriceList\0GetBranchCodeName\0"
    "GetChejanData\0nFid\0GetCodeListByMarket\0sMarket\0GetCommData\0strTrCode\0"
    "strRecordName\0strItemName\0GetCommDataEx\0GetCommRealData\0GetConditionLoad\0"
    "GetConditionNameList\0GetConnectState\0GetDataCount\0GetFutureCodeByIndex\0"
    "GetFutureList\0GetLoginInfo\0sTag\0GetMarketType\0GetMasterCodeName\0GetMasterConstruction\0"
    "GetMasterLastPrice\0GetMasterListedStockCnt\0GetMasterListedStockDate\0"
    "GetMasterStockState\0GetMonthList\0GetOptionATM\0GetOptionCode\0strActPrice\0nCp\0"
    "strMonth\0GetOptionCodeByActPrice\0nTick\0GetOptionCodeByMonth\0GetOutputValue\0"
    "nRepeatIdx\0nItemIdx\0GetRepeatCnt\0sRecordName\0GetSActPriceList\0strBaseAssetGb\0"
    "GetSFOBasisAssetList\0GetSFutureCodeByIndex\0strBaseAssetCode\0GetSFutureList\0"
    "GetSMonthList\0GetSOptionATM\0GetSOptionCode\0GetSOptionCodeByActPrice\0"
    "GetSOptionCodeByMonth\0GetThemeGroupCode\0strThemeCode\0GetThemeGroupList\0nType\0"
    "KOA_Functions\0sFunctionName\0sParam\0SendCondition\0strScrNo\0strConditionName\0"
    "nSearch\0SendConditionStop\0SendOrder\0sAccNo\0nOrderType\0sCode\0nQty\0nPrice\0"
    "sHogaGb\0sOrgOrderNo\0SendOrderCredit\0sCreditGb\0sLoanDate\0SendOrderFO\0lOrdKind\0"
    "sSlbyTp\0sOrdTp\0lQty\0sPrice\0sOrgOrdNo\0SetInfoData\0sInfoData\0SetInputValue\0sID\0"
    "sValue\0SetOutputFID\0SetRealReg\0strScreenNo\0strCodeList\0strFidList\0strOptType\0"
    "SetRealRemove\0strDelCode\0control\0KHOpenAPILib::KHOpenAPI\0Event Interface 1\0"
    "_DKHOpenAPIEvents\0Interface 0\0_DKHOpenAPI\0OnEventConnect\0nErrCode\0"
    "OnReceiveChejanData\0sGubun\0nItemCnt\0sFIdList\0OnReceiveConditionVer\0lRet\0sMsg\0"
    "OnReceiveInvestRealData\0sRealKey\0OnReceiveMsg\0sScrNo\0OnReceiveRealCondition\0"
    "strType\0strConditionIndex\0OnReceiveRealData\0sRealData\0OnReceiveTrCondition\0"
    "nNext\0OnReceiveTrData\0sPrevNext\0nDataLength\0sErrorCode\0sMessage\0sSplmMsg\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_KHOpenAPILib___DKHOpenAPI[] = {

 // content:
    7, // revision
    0,  // classname
    0, 0, // classinfo
    61, 14, // methods
    1, 640, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 319, 2, 5,
    7, 1, 328, 2, 5,
    9, 3, 331, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 0, 338, 2, 9,
    13, 5, 339, 2, 9,
    19, 3, 350, 2, 9,
    23, 6, 357, 2, 9,
    28, 4, 370, 2, 9,
    31, 0, 379, 2, 9,
    32, 1, 380, 2, 9,
    34, 0, 383, 2, 9,
    35, 0, 384, 2, 9,
    36, 0, 385, 2, 9,
    37, 1, 386, 2, 9,
    39, 1, 389, 2, 9,
    41, 4, 392, 2, 9,
    45, 2, 401, 2, 9,
    46, 2, 406, 2, 9,
    47, 0, 411, 2, 9,
    48, 0, 412, 2, 9,
    49, 0, 413, 2, 9,
    50, 1, 414, 2, 9,
    51, 1, 417, 2, 9,
    52, 0, 420, 2, 9,
    53, 1, 421, 2, 9,
    55, 1, 424, 2, 9,
    56, 1, 427, 2, 9,
    57, 1, 430, 2, 9,
    58, 1, 433, 2, 9,
    59, 1, 436, 2, 9,
    60, 1, 439, 2, 9,
    61, 1, 442, 2, 9,
    62, 0, 445, 2, 9,
    63, 0, 446, 2, 9,
    64, 3, 447, 2, 9,
    68, 3, 454, 2, 9,
    70, 3, 461, 2, 9,
    71, 3, 468, 2, 9,
    74, 2, 475, 2, 9,
    76, 1, 480, 2, 9,
    78, 0, 483, 2, 9,
    79, 2, 484, 2, 9,
    81, 1, 489, 2, 9,
    82, 1, 492, 2, 9,
    83, 1, 495, 2, 9,
    84, 4, 498, 2, 9,
    85, 4, 507, 2, 9,
    86, 4, 516, 2, 9,
    87, 1, 525, 2, 9,
    89, 1, 528, 2, 9,
    91, 2, 531, 2, 9,
    94, 4, 536, 2, 9,
    98, 3, 545, 2, 9,
    99, 9, 552, 2, 9,
    107, 11, 571, 2, 9,
    110, 10, 594, 2, 9,
    117, 1, 615, 2, 9,
    119, 2, 618, 2, 9,
    122, 1, 623, 2, 9,
    123, 4, 626, 2, 9,
    128, 2, 635, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Int,
    QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::QString, 14, 15, 16, 17, 18,
    QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 20, 21, 22,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::QString, QMetaType::QString, 24, 25, 26, 27, 21, 22,
    QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::QString, 21, 29, 30, 22,
    QMetaType::Void,
    QMetaType::Void, QMetaType::QString, 33,
    QMetaType::QString,
    QMetaType::QString,
    QMetaType::QString,
    QMetaType::QString, QMetaType::Int, 38,
    QMetaType::QString, QMetaType::QString, 40,
    QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::QString, 42, 43, 17, 44,
    QMetaType::QVariant, QMetaType::QString, QMetaType::QString, 42, 43,
    QMetaType::QString, QMetaType::QString, QMetaType::Int, 29, 38,
    QMetaType::Int,
    QMetaType::QString,
    QMetaType::Int,
    QMetaType::Int, QMetaType::QString, 43,
    QMetaType::QString, QMetaType::Int, 17,
    QMetaType::QString,
    QMetaType::QString, QMetaType::QString, 54,
    QMetaType::Int, QMetaType::QString, 29,
    QMetaType::QString, QMetaType::QString, 29,
    QMetaType::QString, QMetaType::QString, 29,
    QMetaType::QString, QMetaType::QString, 29,
    QMetaType::Int, QMetaType::QString, 29,
    QMetaType::QString, QMetaType::QString, 29,
    QMetaType::QString, QMetaType::QString, 29,
    QMetaType::QString,
    QMetaType::QString,
    QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::QString, 65, 66, 67,
    QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::Int, 29, 66, 69,
    QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::QString, 29, 66, 67,
    QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::Int, 43, 72, 73,
    QMetaType::Int, QMetaType::QString, QMetaType::QString, 29, 75,
    QMetaType::QString, QMetaType::QString, 77,
    QMetaType::QString,
    QMetaType::QString, QMetaType::QString, QMetaType::Int, 80, 17,
    QMetaType::QString, QMetaType::QString, 80,
    QMetaType::QString, QMetaType::QString, 77,
    QMetaType::QString, QMetaType::QString, 77,
    QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::QString, 77, 65, 66, 67,
    QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::Int, 77, 29, 66, 69,
    QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::QString, 77, 29, 66, 67,
    QMetaType::QString, QMetaType::QString, 88,
    QMetaType::QString, QMetaType::Int, 90,
    QMetaType::QString, QMetaType::QString, QMetaType::QString, 92, 93,
    QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::Int, 95, 96, 17, 97,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, QMetaType::Int, 95, 96, 17,
    QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::QString, QMetaType::Int, QMetaType::Int, QMetaType::QString, QMetaType::QString, 21, 22, 100, 101, 102, 103, 104, 105, 106,
    QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::QString, QMetaType::Int, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::QString, 21, 22, 100, 101, 102, 103, 104, 105, 108, 109, 106,
    QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::QString, QMetaType::QString, 21, 22, 100, 102, 111, 112, 113, 114, 115, 116,
    QMetaType::Int, QMetaType::QString, 118,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, 120, 121,
    QMetaType::Int, QMetaType::QString, 120,
    QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::QString, 124, 125, 126, 127,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, 95, 129,

 // properties: name, type, flags
    130, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject _DKHOpenAPI::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_KHOpenAPILib___DKHOpenAPI, 0, 0, 0 }
};

void *_DKHOpenAPI::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "KHOpenAPILib::_DKHOpenAPI"))
        return static_cast<void*>(const_cast<_DKHOpenAPI*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_KHOpenAPILib__KHOpenAPI[] = {

 // content:
    7, // revision
    131,  // classname
    2, 14, // classinfo
    70, 18, // methods
    0, 0, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    12, // signal count

 // classinfo: key, value
    132, 133,
    134, 135,

// signal: name, argc, parameters, tag, flags
    136, 1, 368, 2, 5,
    138, 3, 371, 2, 5,
    142, 2, 378, 2, 5,
    145, 1, 383, 2, 5,
    147, 4, 386, 2, 5,
    149, 4, 395, 2, 5,
    152, 3, 404, 2, 5,
    154, 5, 411, 2, 5,
    156, 9, 422, 2, 5,
    1, 4, 441, 2, 5,
    7, 1, 450, 2, 5,
    9, 3, 453, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 0, 460, 2, 9,
    13, 5, 461, 2, 9,
    19, 3, 472, 2, 9,
    23, 6, 479, 2, 9,
    28, 4, 492, 2, 9,
    31, 0, 501, 2, 9,
    32, 1, 502, 2, 9,
    34, 0, 505, 2, 9,
    35, 0, 506, 2, 9,
    36, 0, 507, 2, 9,
    37, 1, 508, 2, 9,
    39, 1, 511, 2, 9,
    41, 4, 514, 2, 9,
    45, 2, 523, 2, 9,
    46, 2, 528, 2, 9,
    47, 0, 533, 2, 9,
    48, 0, 534, 2, 9,
    49, 0, 535, 2, 9,
    50, 1, 536, 2, 9,
    51, 1, 539, 2, 9,
    52, 0, 542, 2, 9,
    53, 1, 543, 2, 9,
    55, 1, 546, 2, 9,
    56, 1, 549, 2, 9,
    57, 1, 552, 2, 9,
    58, 1, 555, 2, 9,
    59, 1, 558, 2, 9,
    60, 1, 561, 2, 9,
    61, 1, 564, 2, 9,
    62, 0, 567, 2, 9,
    63, 0, 568, 2, 9,
    64, 3, 569, 2, 9,
    68, 3, 576, 2, 9,
    70, 3, 583, 2, 9,
    71, 3, 590, 2, 9,
    74, 2, 597, 2, 9,
    76, 1, 602, 2, 9,
    78, 0, 605, 2, 9,
    79, 2, 606, 2, 9,
    81, 1, 611, 2, 9,
    82, 1, 614, 2, 9,
    83, 1, 617, 2, 9,
    84, 4, 620, 2, 9,
    85, 4, 629, 2, 9,
    86, 4, 638, 2, 9,
    87, 1, 647, 2, 9,
    89, 1, 650, 2, 9,
    91, 2, 653, 2, 9,
    94, 4, 658, 2, 9,
    98, 3, 667, 2, 9,
    99, 9, 674, 2, 9,
    107, 11, 693, 2, 9,
    110, 10, 716, 2, 9,
    117, 1, 737, 2, 9,
    119, 2, 740, 2, 9,
    122, 1, 745, 2, 9,
    123, 4, 748, 2, 9,
    128, 2, 757, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, 137,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::QString, 139, 140, 141,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, 143, 144,
    QMetaType::Void, QMetaType::QString, 146,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::QString, 148, 21, 29, 144,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::QString, 29, 150, 96, 151,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, QMetaType::QString, 146, 15, 153,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::Int, 148, 125, 96, 17, 155,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 148, 21, 29, 75, 157, 158, 159, 160, 161,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Int,
    QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::QString, 14, 15, 16, 17, 18,
    QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 20, 21, 22,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::QString, QMetaType::QString, 24, 25, 26, 27, 21, 22,
    QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::QString, 21, 29, 30, 22,
    QMetaType::Void,
    QMetaType::Void, QMetaType::QString, 33,
    QMetaType::QString,
    QMetaType::QString,
    QMetaType::QString,
    QMetaType::QString, QMetaType::Int, 38,
    QMetaType::QString, QMetaType::QString, 40,
    QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::QString, 42, 43, 17, 44,
    QMetaType::QVariant, QMetaType::QString, QMetaType::QString, 42, 43,
    QMetaType::QString, QMetaType::QString, QMetaType::Int, 29, 38,
    QMetaType::Int,
    QMetaType::QString,
    QMetaType::Int,
    QMetaType::Int, QMetaType::QString, 43,
    QMetaType::QString, QMetaType::Int, 17,
    QMetaType::QString,
    QMetaType::QString, QMetaType::QString, 54,
    QMetaType::Int, QMetaType::QString, 29,
    QMetaType::QString, QMetaType::QString, 29,
    QMetaType::QString, QMetaType::QString, 29,
    QMetaType::QString, QMetaType::QString, 29,
    QMetaType::Int, QMetaType::QString, 29,
    QMetaType::QString, QMetaType::QString, 29,
    QMetaType::QString, QMetaType::QString, 29,
    QMetaType::QString,
    QMetaType::QString,
    QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::QString, 65, 66, 67,
    QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::Int, 29, 66, 69,
    QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::QString, 29, 66, 67,
    QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::Int, 43, 72, 73,
    QMetaType::Int, QMetaType::QString, QMetaType::QString, 29, 75,
    QMetaType::QString, QMetaType::QString, 77,
    QMetaType::QString,
    QMetaType::QString, QMetaType::QString, QMetaType::Int, 80, 17,
    QMetaType::QString, QMetaType::QString, 80,
    QMetaType::QString, QMetaType::QString, 77,
    QMetaType::QString, QMetaType::QString, 77,
    QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::QString, 77, 65, 66, 67,
    QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::Int, 77, 29, 66, 69,
    QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::QString, 77, 29, 66, 67,
    QMetaType::QString, QMetaType::QString, 88,
    QMetaType::QString, QMetaType::Int, 90,
    QMetaType::QString, QMetaType::QString, QMetaType::QString, 92, 93,
    QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::Int, 95, 96, 17, 97,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, QMetaType::Int, 95, 96, 17,
    QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::QString, QMetaType::Int, QMetaType::Int, QMetaType::QString, QMetaType::QString, 21, 22, 100, 101, 102, 103, 104, 105, 106,
    QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::QString, QMetaType::Int, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::QString, 21, 22, 100, 101, 102, 103, 104, 105, 108, 109, 106,
    QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::QString, QMetaType::QString, 21, 22, 100, 102, 111, 112, 113, 114, 115, 116,
    QMetaType::Int, QMetaType::QString, 118,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, 120, 121,
    QMetaType::Int, QMetaType::QString, 120,
    QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::QString, 124, 125, 126, 127,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, 95, 129,

    0 // eod
};

const QMetaObject KHOpenAPI::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_KHOpenAPILib__KHOpenAPI, 0, 0, 0 }
};

void *KHOpenAPI::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "KHOpenAPILib::KHOpenAPI"))
        return static_cast<void*>(const_cast<KHOpenAPI*>(this));
    return QAxWidget::qt_metacast(_clname);
}

