// Created by cgo -godefs - DO NOT EDIT
// cgo -godefs D:\Go\src\github.com\ghts\ghts\api\NH\wmca_ctype_orig.go

package NH

type AccountInfo struct {
	AccountNo	[11]int8
	AccountName	[40]int8
	Act_pdt_cdz3	[3]int8
	Amn_tab_cdz4	[4]int8
	ExpirationDate8	[8]int8
	Granted		int8
	Filler		[189]int8
}
type LoginInfo struct {
	Date		[14]int8
	ServerName	[15]int8
	UserID		[8]int8
	AccountCount	[3]int8
	Accountlist	[999]AccountInfo
}
type LoginBlock struct {
	TrIndex		int32
	LoginInfo	*LoginInfo
}

type MsgHeader struct {
	MsgCode	[5]int8
	UsrMsg	[80]int8
}

type Received struct {
	BlockName	*int8
	DataString	*int8
	Length		int32
}
type OutDataBlock struct {
	TrIndex		int32
	DataStruct	*Received
}

type Tc1101OutBlock struct {
	Code			[6]int8
	X_Code			int8
	Title			[13]int8
	X_Title			int8
	MarketPrice		[7]int8
	X_MarketPrice		int8
	DiffSign		[1]int8
	X_DiffSign		int8
	Diff			[6]int8
	X_Diff			int8
	DiffRate		[5]int8
	X_DiffRate		int8
	OfferPrice		[7]int8
	X_OfferPrice		int8
	BidPrice		[7]int8
	X_BidPrice		int8
	Volume			[9]int8
	X_Volume		int8
	TrVolRate		[6]int8
	X_TrVolRate		int8
	FloatRate		[5]int8
	X_FloatRate		int8
	TrAmount		[9]int8
	X_TrAmount		int8
	UpLmtPrice		[7]int8
	X_UpLmtPrice		int8
	High			[7]int8
	X_High			int8
	Open			[7]int8
	X_Open			int8
	VsOpenSign		[1]int8
	X_VsOpenSign		int8
	VsOpenDiff		[6]int8
	X_VsOpenDiff		int8
	Low			[7]int8
	X_Low			int8
	LowLmtPrice		[7]int8
	X_LowLmtPrice		int8
	QuoteTime		[8]int8
	X_QuoteTime		int8
	OfferPrice1		[7]int8
	X_OfferPrice1		int8
	OfferPrice2		[7]int8
	X_OfferPrice2		int8
	OfferPrice3		[7]int8
	X_OfferPrice3		int8
	OfferPrice4		[7]int8
	X_OfferPrice4		int8
	OfferPrice5		[7]int8
	X_OfferPrice5		int8
	OfferPrice6		[7]int8
	X_OfferPrice6		int8
	OfferPrice7		[7]int8
	X_OfferPrice7		int8
	OfferPrice8		[7]int8
	X_OfferPrice8		int8
	OfferPrice9		[7]int8
	X_OfferPrice9		int8
	OfferPrice10		[7]int8
	X_OfferPrice10		int8
	BidPrice1		[7]int8
	X_BidPrice1		int8
	BidPrice2		[7]int8
	X_BidPrice2		int8
	BidPrice3		[7]int8
	X_BidPrice3		int8
	BidPrice4		[7]int8
	X_BidPrice4		int8
	BidPrice5		[7]int8
	X_BidPrice5		int8
	BidPrice6		[7]int8
	X_BidPrice6		int8
	BidPrice7		[7]int8
	X_BidPrice7		int8
	BidPrice8		[7]int8
	X_BidPrice8		int8
	BidPrice9		[7]int8
	X_BidPrice9		int8
	BidPrice10		[7]int8
	X_BidPrice10		int8
	OfferVolume1		[9]int8
	X_OfferVolume1		int8
	OfferVolume2		[9]int8
	X_OfferVolume2		int8
	OfferVolume3		[9]int8
	X_OfferVolume3		int8
	OfferVolume4		[9]int8
	X_OfferVolume4		int8
	OfferVolume5		[9]int8
	X_OfferVolume5		int8
	OfferVolume6		[9]int8
	X_OfferVolume6		int8
	OfferVolume7		[9]int8
	X_OfferVolume7		int8
	OfferVolume8		[9]int8
	X_OfferVolume8		int8
	OfferVolume9		[9]int8
	X_OfferVolume9		int8
	OfferVolume10		[9]int8
	X_OfferVolume10		int8
	BidVolume1		[9]int8
	X_BidVolume1		int8
	BidVolume2		[9]int8
	X_BidVolume2		int8
	BidVolume3		[9]int8
	X_BidVolume3		int8
	BidVolume4		[9]int8
	X_BidVolume4		int8
	BidVolume5		[9]int8
	X_BidVolume5		int8
	BidVolume6		[9]int8
	X_BidVolume6		int8
	BidVolume7		[9]int8
	X_BidVolume7		int8
	BidVolume8		[9]int8
	X_BidVolume8		int8
	BidVolume9		[9]int8
	X_BidVolume9		int8
	BidVolume10		[9]int8
	X_BidVolume10		int8
	OfferVolTot		[9]int8
	X_OfferVolTot		int8
	BidVolTot		[9]int8
	X_BidVolTot		int8
	OfferVolAfterHour	[9]int8
	X_OfferVolAfterHour	int8
	BidVolAfterHour		[9]int8
	X_BidVolAfterHour	int8
	PivotUp2		[7]int8
	X_PivotUp2		int8
	PivotUp1		[7]int8
	X_PivotUp1		int8
	PivotPrice		[7]int8
	X_PivotPrice		int8
	PivotDown1		[7]int8
	X_PivotDown1		int8
	PivotDown2		[7]int8
	X_PivotDown2		int8
	Market			[6]int8
	X_Market		int8
	Sector			[18]int8
	X_Sector		int8
	CapSize			[6]int8
	X_CapSize		int8
	SettleMonth		[16]int8
	X_SettleMonth		int8
	MarketAction1		[16]int8
	X_MarketAction1		int8
	MarketAction2		[16]int8
	X_MarketAction2		int8
	MarketAction3		[16]int8
	X_MarketAction3		int8
	MarketAction4		[16]int8
	X_MarketAction4		int8
	MarketAction5		[16]int8
	X_MarketAction5		int8
	MarketAction6		[16]int8
	X_MarketAction6		int8
	ConvertBond		[6]int8
	X_ConvertBond		int8
	NominalPrice		[7]int8
	X_NominalPrice		int8
	PrevPriceTitle		[12]int8
	X_PrevPriceTitle	int8
	PrevPrice		[7]int8
	X_PrevPrice		int8
	MortgageValue		[7]int8
	X_MortgageValue		int8
	PublicOfferPrice	[7]int8
	X_PublicOfferPrice	int8
	High5Day		[7]int8
	X_High5Day		int8
	Low5Day			[7]int8
	X_Low5Day		int8
	High20Day		[7]int8
	X_High20Day		int8
	Low20Day		[7]int8
	X_Low20Day		int8
	High1Year		[7]int8
	X_High1Year		int8
	High1YearDate		[4]int8
	X_High1YearDate		int8
	Low1Year		[7]int8
	X_Low1Year		int8
	Low1YearDate		[4]int8
	X_Low1YearDate		int8
	FloatVolume		[8]int8
	X_FloatVolume		int8
	ListVolBy1000		[12]int8
	X_ListVolBy1000		int8
	MarketCapital		[9]int8
	X_MarketCapital		int8
	TraderInfoTime		[5]int8
	X_TraderInfoTime	int8
	Seller1			[6]int8
	X_Seller1		int8
	Buyer1			[6]int8
	X_Buyer1		int8
	Seller1Volumn		[9]int8
	X_Seller1Volume		int8
	Buyer1Volume		[9]int8
	X_Buyer1Volume		int8
	Seller2			[6]int8
	X_Seller2		int8
	Buyer2			[6]int8
	X_Buyer2		int8
	Seller2Volumn		[9]int8
	X_Seller2Volume		int8
	Buyer2Volume		[9]int8
	X_Buyer2Volume		int8
	Seller3			[6]int8
	X_Seller3		int8
	Buyer3			[6]int8
	X_Buyer3		int8
	Seller3Volumn		[9]int8
	X_Seller3Volume		int8
	Buyer3Volume		[9]int8
	X_Buyer3Volume		int8
	Seller4			[6]int8
	X_Seller4		int8
	Buyer4			[6]int8
	X_Buyer4		int8
	Seller4Volumn		[9]int8
	X_Seller4Volume		int8
	Buyer4Volume		[9]int8
	X_Buyer4Volume		int8
	Seller5			[6]int8
	X_Seller5		int8
	Buyer5			[6]int8
	X_Buyer5		int8
	Seller5Volumn		[9]int8
	X_Seller5Volume		int8
	Buyer5Volume		[9]int8
	X_Buyer5Volume		int8
	ForeignSellVolume	[9]int8
	X_ForeignSellVolume	int8
	ForeignBuyVolume	[9]int8
	X_ForeignBuyVolume	int8
	ForeignTime		[6]int8
	X_ForeignTime		int8
	ForeignHoldingRate	[5]int8
	X_ForeignHoldingRate	int8
	SettleDate		[4]int8
	X_SettleDate		int8
	DebtPercent		[5]int8
	X_DebtPercent		int8
	RightsIssueDate		[4]int8
	X_RightsIssueDate	int8
	BonusIssueDate		[4]int8
	X_BonusIssueDate	int8
	RightsIssueRate		[5]int8
	X_RightsIssueRate	int8
	ForeignFloatVol		[10]int8
	X_ForeignFloatVol	int8
	BonusIssueRate		[5]int8
	X_BonusIssueRate	int8
	TreasuryStock		[1]int8
	X_TreasuryStock		int8
	Date			[8]int8
	X_IPO_Date		int8
	MajorHoldRate		[5]int8
	X_MajorHoldRate		int8
	MajorHoldInfoDate	[6]int8
	X_MajorHoldInfoDate	int8
	FourLeafClover		[1]int8
	X_FourLeafClover	int8
	MarginRate		[1]int8
	X_MarginRate		int8
	Capital			[9]int8
	X_Capital		int8
	SellTotalSum		[9]int8
	X_SellTotalSum		int8
	BuyTotalSum		[9]int8
	X_BuyTotalSum		int8
	Title2			[21]int8
	X_Title2		int8
	BackdoorListing		[1]int8
	X_BackdoorListing	int8
	FloatRate2		[6]int8
	X_FloatRate2		int8
	Market2			[6]int8
	X_Market2		int8
	DebtTrDate		[4]int8
	X_DebtTrDate		int8
	DebtTrPercent		[5]int8
	X_DebtTrPercent		int8
	PER			[5]int8
	X_PER			int8
	DebtLimit		[1]int8
	X_DebtLimit		int8
	WeightAvgPrice		[7]int8
	X_WeightAvgPrice	int8
	ListedVolume		[12]int8
	X_ListedVolume		int8
	AddListing		[12]int8
	X_AddListing		int8
	Comment			[100]int8
	X_Comment		int8
	PrevVolume		[9]int8
	X_PrevVolume		int8
	VsPrevSign		[1]int8
	X_VsPrevSign		int8
	VsPrevDiff		[6]int8
	X_VsPrevDiff		int8
	High1Year2		[7]int8
	X_High1Year2		int8
	High1YearDate2		[4]int8
	X_High1YearDate2	int8
	Low1Year2		[7]int8
	X_Low1Year2		int8
	Low1YearDate2		[4]int8
	X_Low1YearDate2		int8
	ForeignHoldNo		[15]int8
	X_ForeignHoldNo		int8
	ForeignLmtPercent	[5]int8
	X_ForeignLmtPercent	int8
	TrUnitVolume		[5]int8
	X_TrUnitVolume		int8
	BlackPoolOfferBid	[1]int8
	X_BlackPoolOfferBid	int8
	BlackPoolExist		[1]int8
	X_BlackPoolExist	int8
}
type Tc1101OutBlock2 struct {
	Time		[8]int8
	X_Time		int8
	MarketPrice	[7]int8
	X_MarketPrice	int8
	DiffSign	[1]int8
	X_DiffSign	int8
	Diff		[6]int8
	X_Diff		int8
	OfferPrice	[7]int8
	X_OfferPrice	int8
	BidPrice	[7]int8
	X_BidPrice	int8
	DiffVolume	[8]int8
	X_DiffVolume	int8
	Volume		[9]int8
	X_Volume	int8
}
