/****************************************************************************
**
** Namespace KHOpenAPILib generated by dumpcpp v5.12.7 using
** dumpcpp KHOPENAPI.KHOpenAPICtrl.1 -o C:\Users\kuh\go\src\github.com\ghts\ghts\kiwoom\base\kiwoom
** from the type library C:\OpenAPI\KHOpenAPI.ocx
**
****************************************************************************/

#ifndef QAX_DUMPCPP_KIWOOM_H
#define QAX_DUMPCPP_KIWOOM_H

// Define this symbol to __declspec(dllexport) or __declspec(dllimport)
#ifndef KHOPENAPILIB_EXPORT
#define KHOPENAPILIB_EXPORT
#endif

#include <QAxObject>
#include <QAxWidget>
#include <QDateTime>
#include <QPixmap>

struct IDispatch;


// Referenced namespace

namespace KHOpenAPILib {


class KHOPENAPILIB_EXPORT _DKHOpenAPI : public QAxObject
{
public:
    _DKHOpenAPI(IDispatch *subobject = 0, QAxObject *parent = 0)
    : QAxObject((IUnknown*)subobject, parent) {
        internalRelease();
    }

    /*
    Method CommConnect
    */
    inline int CommConnect();

    /*
    Method CommGetData
    */
    inline QString CommGetData(const QString& sJongmokCode, const QString& sRealType, const QString& sFieldName, int nIndex, const QString& sInnerFieldName);

    /*
    Method CommInvestRqData
    */
    inline int CommInvestRqData(const QString& sMarketGb, const QString& sRQName, const QString& sScreenNo);

    /*
    Method CommKwRqData
    */
    inline int CommKwRqData(const QString& sArrCode, int bNext, int nCodeCount, int nTypeFlag, const QString& sRQName, const QString& sScreenNo);

    /*
    Method CommRqData
    */
    inline int CommRqData(const QString& sRQName, const QString& sTrCode, int nPrevNext, const QString& sScreenNo);

    /*
    Method CommTerminate
    */
    inline void CommTerminate();

    /*
    Method DisconnectRealData
    */
    inline void DisconnectRealData(const QString& sScnNo);

    /*
    Method GetAPIModulePath
    */
    inline QString GetAPIModulePath();

    /*
    Method GetActPriceList
    */
    inline QString GetActPriceList();

    /*
    Method GetBranchCodeName
    */
    inline QString GetBranchCodeName();

    /*
    Method GetChejanData
    */
    inline QString GetChejanData(int nFid);

    /*
    Method GetCodeListByMarket
    */
    inline QString GetCodeListByMarket(const QString& sMarket);

    /*
    Method GetCommData
    */
    inline QString GetCommData(const QString& strTrCode, const QString& strRecordName, int nIndex, const QString& strItemName);

    /*
    Method GetCommDataEx
    */
    inline QVariant GetCommDataEx(const QString& strTrCode, const QString& strRecordName);

    /*
    Method GetCommRealData
    */
    inline QString GetCommRealData(const QString& sTrCode, int nFid);

    /*
    Method GetConditionLoad
    */
    inline int GetConditionLoad();

    /*
    Method GetConditionNameList
    */
    inline QString GetConditionNameList();

    /*
    Method GetConnectState
    */
    inline int GetConnectState();

    /*
    Method GetDataCount
    */
    inline int GetDataCount(const QString& strRecordName);

    /*
    Method GetFutureCodeByIndex
    */
    inline QString GetFutureCodeByIndex(int nIndex);

    /*
    Method GetFutureList
    */
    inline QString GetFutureList();

    /*
    Method GetLoginInfo
    */
    inline QString GetLoginInfo(const QString& sTag);

    /*
    Method GetMarketType
    */
    inline int GetMarketType(const QString& sTrCode);

    /*
    Method GetMasterCodeName
    */
    inline QString GetMasterCodeName(const QString& sTrCode);

    /*
    Method GetMasterConstruction
    */
    inline QString GetMasterConstruction(const QString& sTrCode);

    /*
    Method GetMasterLastPrice
    */
    inline QString GetMasterLastPrice(const QString& sTrCode);

    /*
    Method GetMasterListedStockCnt
    */
    inline int GetMasterListedStockCnt(const QString& sTrCode);

    /*
    Method GetMasterListedStockDate
    */
    inline QString GetMasterListedStockDate(const QString& sTrCode);

    /*
    Method GetMasterStockState
    */
    inline QString GetMasterStockState(const QString& sTrCode);

    /*
    Method GetMonthList
    */
    inline QString GetMonthList();

    /*
    Method GetOptionATM
    */
    inline QString GetOptionATM();

    /*
    Method GetOptionCode
    */
    inline QString GetOptionCode(const QString& strActPrice, int nCp, const QString& strMonth);

    /*
    Method GetOptionCodeByActPrice
    */
    inline QString GetOptionCodeByActPrice(const QString& sTrCode, int nCp, int nTick);

    /*
    Method GetOptionCodeByMonth
    */
    inline QString GetOptionCodeByMonth(const QString& sTrCode, int nCp, const QString& strMonth);

    /*
    Method GetOutputValue
    */
    inline QString GetOutputValue(const QString& strRecordName, int nRepeatIdx, int nItemIdx);

    /*
    Method GetRepeatCnt
    */
    inline int GetRepeatCnt(const QString& sTrCode, const QString& sRecordName);

    /*
    Method GetSActPriceList
    */
    inline QString GetSActPriceList(const QString& strBaseAssetGb);

    /*
    Method GetSFOBasisAssetList
    */
    inline QString GetSFOBasisAssetList();

    /*
    Method GetSFutureCodeByIndex
    */
    inline QString GetSFutureCodeByIndex(const QString& strBaseAssetCode, int nIndex);

    /*
    Method GetSFutureList
    */
    inline QString GetSFutureList(const QString& strBaseAssetCode);

    /*
    Method GetSMonthList
    */
    inline QString GetSMonthList(const QString& strBaseAssetGb);

    /*
    Method GetSOptionATM
    */
    inline QString GetSOptionATM(const QString& strBaseAssetGb);

    /*
    Method GetSOptionCode
    */
    inline QString GetSOptionCode(const QString& strBaseAssetGb, const QString& strActPrice, int nCp, const QString& strMonth);

    /*
    Method GetSOptionCodeByActPrice
    */
    inline QString GetSOptionCodeByActPrice(const QString& strBaseAssetGb, const QString& sTrCode, int nCp, int nTick);

    /*
    Method GetSOptionCodeByMonth
    */
    inline QString GetSOptionCodeByMonth(const QString& strBaseAssetGb, const QString& sTrCode, int nCp, const QString& strMonth);

    /*
    Method GetThemeGroupCode
    */
    inline QString GetThemeGroupCode(const QString& strThemeCode);

    /*
    Method GetThemeGroupList
    */
    inline QString GetThemeGroupList(int nType);

    /*
    Method KOA_Functions
    */
    inline QString KOA_Functions(const QString& sFunctionName, const QString& sParam);

    /*
    Method SendCondition
    */
    inline int SendCondition(const QString& strScrNo, const QString& strConditionName, int nIndex, int nSearch);

    /*
    Method SendConditionStop
    */
    inline void SendConditionStop(const QString& strScrNo, const QString& strConditionName, int nIndex);

    /*
    Method SendOrder
    */
    inline int SendOrder(const QString& sRQName, const QString& sScreenNo, const QString& sAccNo, int nOrderType, const QString& sCode, int nQty, int nPrice, const QString& sHogaGb, const QString& sOrgOrderNo);

    /*
    Method SendOrderCredit
    */
    inline int SendOrderCredit(const QString& sRQName, const QString& sScreenNo, const QString& sAccNo, int nOrderType, const QString& sCode, int nQty, int nPrice, const QString& sHogaGb, const QString& sCreditGb, const QString& sLoanDate, const QString& sOrgOrderNo);

    /*
    Method SendOrderFO
    */
    inline int SendOrderFO(const QString& sRQName, const QString& sScreenNo, const QString& sAccNo, const QString& sCode, int lOrdKind, const QString& sSlbyTp, const QString& sOrdTp, int lQty, const QString& sPrice, const QString& sOrgOrdNo);

    /*
    Method SetInfoData
    */
    inline int SetInfoData(const QString& sInfoData);

    /*
    Method SetInputValue
    */
    inline void SetInputValue(const QString& sID, const QString& sValue);

    /*
    Method SetOutputFID
    */
    inline int SetOutputFID(const QString& sID);

    /*
    Method SetRealReg
    */
    inline int SetRealReg(const QString& strScreenNo, const QString& strCodeList, const QString& strFidList, const QString& strOptType);

    /*
    Method SetRealRemove
    */
    inline void SetRealRemove(const QString& strScrNo, const QString& strDelCode);

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

// skipping event interface _DKHOpenAPIEvents

// Actual coclasses
class KHOPENAPILIB_EXPORT KHOpenAPI : public QAxWidget
{
public:
    KHOpenAPI(QWidget *parent = 0, Qt::WindowFlags f = 0) : QAxWidget(parent, f) {
        setControl(QStringLiteral("{a1574a0d-6bfa-4bd7-9020-ded88711818d}"));
    }

    KHOpenAPI(_DKHOpenAPI *iface) : QAxWidget() {
        initializeFrom(iface);
        delete iface;
    }

    /*
    Method CommConnect
    */
    inline int CommConnect();

    /*
    Method CommGetData
    */
    inline QString CommGetData(const QString& sJongmokCode, const QString& sRealType, const QString& sFieldName, int nIndex, const QString& sInnerFieldName);

    /*
    Method CommInvestRqData
    */
    inline int CommInvestRqData(const QString& sMarketGb, const QString& sRQName, const QString& sScreenNo);

    /*
    Method CommKwRqData
    */
    inline int CommKwRqData(const QString& sArrCode, int bNext, int nCodeCount, int nTypeFlag, const QString& sRQName, const QString& sScreenNo);

    /*
    Method CommRqData
    */
    inline int CommRqData(const QString& sRQName, const QString& sTrCode, int nPrevNext, const QString& sScreenNo);

    /*
    Method CommTerminate
    */
    inline void CommTerminate();

    /*
    Method DisconnectRealData
    */
    inline void DisconnectRealData(const QString& sScnNo);

    /*
    Method GetAPIModulePath
    */
    inline QString GetAPIModulePath();

    /*
    Method GetActPriceList
    */
    inline QString GetActPriceList();

    /*
    Method GetBranchCodeName
    */
    inline QString GetBranchCodeName();

    /*
    Method GetChejanData
    */
    inline QString GetChejanData(int nFid);

    /*
    Method GetCodeListByMarket
    */
    inline QString GetCodeListByMarket(const QString& sMarket);

    /*
    Method GetCommData
    */
    inline QString GetCommData(const QString& strTrCode, const QString& strRecordName, int nIndex, const QString& strItemName);

    /*
    Method GetCommDataEx
    */
    inline QVariant GetCommDataEx(const QString& strTrCode, const QString& strRecordName);

    /*
    Method GetCommRealData
    */
    inline QString GetCommRealData(const QString& sTrCode, int nFid);

    /*
    Method GetConditionLoad
    */
    inline int GetConditionLoad();

    /*
    Method GetConditionNameList
    */
    inline QString GetConditionNameList();

    /*
    Method GetConnectState
    */
    inline int GetConnectState();

    /*
    Method GetDataCount
    */
    inline int GetDataCount(const QString& strRecordName);

    /*
    Method GetFutureCodeByIndex
    */
    inline QString GetFutureCodeByIndex(int nIndex);

    /*
    Method GetFutureList
    */
    inline QString GetFutureList();

    /*
    Method GetLoginInfo
    */
    inline QString GetLoginInfo(const QString& sTag);

    /*
    Method GetMarketType
    */
    inline int GetMarketType(const QString& sTrCode);

    /*
    Method GetMasterCodeName
    */
    inline QString GetMasterCodeName(const QString& sTrCode);

    /*
    Method GetMasterConstruction
    */
    inline QString GetMasterConstruction(const QString& sTrCode);

    /*
    Method GetMasterLastPrice
    */
    inline QString GetMasterLastPrice(const QString& sTrCode);

    /*
    Method GetMasterListedStockCnt
    */
    inline int GetMasterListedStockCnt(const QString& sTrCode);

    /*
    Method GetMasterListedStockDate
    */
    inline QString GetMasterListedStockDate(const QString& sTrCode);

    /*
    Method GetMasterStockState
    */
    inline QString GetMasterStockState(const QString& sTrCode);

    /*
    Method GetMonthList
    */
    inline QString GetMonthList();

    /*
    Method GetOptionATM
    */
    inline QString GetOptionATM();

    /*
    Method GetOptionCode
    */
    inline QString GetOptionCode(const QString& strActPrice, int nCp, const QString& strMonth);

    /*
    Method GetOptionCodeByActPrice
    */
    inline QString GetOptionCodeByActPrice(const QString& sTrCode, int nCp, int nTick);

    /*
    Method GetOptionCodeByMonth
    */
    inline QString GetOptionCodeByMonth(const QString& sTrCode, int nCp, const QString& strMonth);

    /*
    Method GetOutputValue
    */
    inline QString GetOutputValue(const QString& strRecordName, int nRepeatIdx, int nItemIdx);

    /*
    Method GetRepeatCnt
    */
    inline int GetRepeatCnt(const QString& sTrCode, const QString& sRecordName);

    /*
    Method GetSActPriceList
    */
    inline QString GetSActPriceList(const QString& strBaseAssetGb);

    /*
    Method GetSFOBasisAssetList
    */
    inline QString GetSFOBasisAssetList();

    /*
    Method GetSFutureCodeByIndex
    */
    inline QString GetSFutureCodeByIndex(const QString& strBaseAssetCode, int nIndex);

    /*
    Method GetSFutureList
    */
    inline QString GetSFutureList(const QString& strBaseAssetCode);

    /*
    Method GetSMonthList
    */
    inline QString GetSMonthList(const QString& strBaseAssetGb);

    /*
    Method GetSOptionATM
    */
    inline QString GetSOptionATM(const QString& strBaseAssetGb);

    /*
    Method GetSOptionCode
    */
    inline QString GetSOptionCode(const QString& strBaseAssetGb, const QString& strActPrice, int nCp, const QString& strMonth);

    /*
    Method GetSOptionCodeByActPrice
    */
    inline QString GetSOptionCodeByActPrice(const QString& strBaseAssetGb, const QString& sTrCode, int nCp, int nTick);

    /*
    Method GetSOptionCodeByMonth
    */
    inline QString GetSOptionCodeByMonth(const QString& strBaseAssetGb, const QString& sTrCode, int nCp, const QString& strMonth);

    /*
    Method GetThemeGroupCode
    */
    inline QString GetThemeGroupCode(const QString& strThemeCode);

    /*
    Method GetThemeGroupList
    */
    inline QString GetThemeGroupList(int nType);

    /*
    Method KOA_Functions
    */
    inline QString KOA_Functions(const QString& sFunctionName, const QString& sParam);

    /*
    Method SendCondition
    */
    inline int SendCondition(const QString& strScrNo, const QString& strConditionName, int nIndex, int nSearch);

    /*
    Method SendConditionStop
    */
    inline void SendConditionStop(const QString& strScrNo, const QString& strConditionName, int nIndex);

    /*
    Method SendOrder
    */
    inline int SendOrder(const QString& sRQName, const QString& sScreenNo, const QString& sAccNo, int nOrderType, const QString& sCode, int nQty, int nPrice, const QString& sHogaGb, const QString& sOrgOrderNo);

    /*
    Method SendOrderCredit
    */
    inline int SendOrderCredit(const QString& sRQName, const QString& sScreenNo, const QString& sAccNo, int nOrderType, const QString& sCode, int nQty, int nPrice, const QString& sHogaGb, const QString& sCreditGb, const QString& sLoanDate, const QString& sOrgOrderNo);

    /*
    Method SendOrderFO
    */
    inline int SendOrderFO(const QString& sRQName, const QString& sScreenNo, const QString& sAccNo, const QString& sCode, int lOrdKind, const QString& sSlbyTp, const QString& sOrdTp, int lQty, const QString& sPrice, const QString& sOrgOrdNo);

    /*
    Method SetInfoData
    */
    inline int SetInfoData(const QString& sInfoData);

    /*
    Method SetInputValue
    */
    inline void SetInputValue(const QString& sID, const QString& sValue);

    /*
    Method SetOutputFID
    */
    inline int SetOutputFID(const QString& sID);

    /*
    Method SetRealReg
    */
    inline int SetRealReg(const QString& strScreenNo, const QString& strCodeList, const QString& strFidList, const QString& strOptType);

    /*
    Method SetRealRemove
    */
    inline void SetRealRemove(const QString& strScrNo, const QString& strDelCode);

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

// member function implementation
#ifndef QAX_DUMPCPP_KHOPENAPILIB_NOINLINES
inline int _DKHOpenAPI::CommConnect()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 8, _a);
    return qax_result;
}

inline QString _DKHOpenAPI::CommGetData(const QString& sJongmokCode, const QString& sRealType, const QString& sFieldName, int nIndex, const QString& sInnerFieldName)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sJongmokCode, (void*)&sRealType, (void*)&sFieldName, (void*)&nIndex, (void*)&sInnerFieldName};
    qt_metacall(QMetaObject::InvokeMetaMethod, 9, _a);
    return qax_result;
}

inline int _DKHOpenAPI::CommInvestRqData(const QString& sMarketGb, const QString& sRQName, const QString& sScreenNo)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sMarketGb, (void*)&sRQName, (void*)&sScreenNo};
    qt_metacall(QMetaObject::InvokeMetaMethod, 10, _a);
    return qax_result;
}

inline int _DKHOpenAPI::CommKwRqData(const QString& sArrCode, int bNext, int nCodeCount, int nTypeFlag, const QString& sRQName, const QString& sScreenNo)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sArrCode, (void*)&bNext, (void*)&nCodeCount, (void*)&nTypeFlag, (void*)&sRQName, (void*)&sScreenNo};
    qt_metacall(QMetaObject::InvokeMetaMethod, 11, _a);
    return qax_result;
}

inline int _DKHOpenAPI::CommRqData(const QString& sRQName, const QString& sTrCode, int nPrevNext, const QString& sScreenNo)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sRQName, (void*)&sTrCode, (void*)&nPrevNext, (void*)&sScreenNo};
    qt_metacall(QMetaObject::InvokeMetaMethod, 12, _a);
    return qax_result;
}

inline void _DKHOpenAPI::CommTerminate()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 13, _a);
}

inline void _DKHOpenAPI::DisconnectRealData(const QString& sScnNo)
{
    void *_a[] = {0, (void*)&sScnNo};
    qt_metacall(QMetaObject::InvokeMetaMethod, 14, _a);
}

inline QString _DKHOpenAPI::GetAPIModulePath()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 15, _a);
    return qax_result;
}

inline QString _DKHOpenAPI::GetActPriceList()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 16, _a);
    return qax_result;
}

inline QString _DKHOpenAPI::GetBranchCodeName()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 17, _a);
    return qax_result;
}

inline QString _DKHOpenAPI::GetChejanData(int nFid)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&nFid};
    qt_metacall(QMetaObject::InvokeMetaMethod, 18, _a);
    return qax_result;
}

inline QString _DKHOpenAPI::GetCodeListByMarket(const QString& sMarket)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sMarket};
    qt_metacall(QMetaObject::InvokeMetaMethod, 19, _a);
    return qax_result;
}

inline QString _DKHOpenAPI::GetCommData(const QString& strTrCode, const QString& strRecordName, int nIndex, const QString& strItemName)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&strTrCode, (void*)&strRecordName, (void*)&nIndex, (void*)&strItemName};
    qt_metacall(QMetaObject::InvokeMetaMethod, 20, _a);
    return qax_result;
}

inline QVariant _DKHOpenAPI::GetCommDataEx(const QString& strTrCode, const QString& strRecordName)
{
    QVariant qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&strTrCode, (void*)&strRecordName};
    qt_metacall(QMetaObject::InvokeMetaMethod, 21, _a);
    return qax_result;
}

inline QString _DKHOpenAPI::GetCommRealData(const QString& sTrCode, int nFid)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sTrCode, (void*)&nFid};
    qt_metacall(QMetaObject::InvokeMetaMethod, 22, _a);
    return qax_result;
}

inline int _DKHOpenAPI::GetConditionLoad()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 23, _a);
    return qax_result;
}

inline QString _DKHOpenAPI::GetConditionNameList()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 24, _a);
    return qax_result;
}

inline int _DKHOpenAPI::GetConnectState()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 25, _a);
    return qax_result;
}

inline int _DKHOpenAPI::GetDataCount(const QString& strRecordName)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&strRecordName};
    qt_metacall(QMetaObject::InvokeMetaMethod, 26, _a);
    return qax_result;
}

inline QString _DKHOpenAPI::GetFutureCodeByIndex(int nIndex)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&nIndex};
    qt_metacall(QMetaObject::InvokeMetaMethod, 27, _a);
    return qax_result;
}

inline QString _DKHOpenAPI::GetFutureList()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 28, _a);
    return qax_result;
}

inline QString _DKHOpenAPI::GetLoginInfo(const QString& sTag)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sTag};
    qt_metacall(QMetaObject::InvokeMetaMethod, 29, _a);
    return qax_result;
}

inline int _DKHOpenAPI::GetMarketType(const QString& sTrCode)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sTrCode};
    qt_metacall(QMetaObject::InvokeMetaMethod, 30, _a);
    return qax_result;
}

inline QString _DKHOpenAPI::GetMasterCodeName(const QString& sTrCode)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sTrCode};
    qt_metacall(QMetaObject::InvokeMetaMethod, 31, _a);
    return qax_result;
}

inline QString _DKHOpenAPI::GetMasterConstruction(const QString& sTrCode)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sTrCode};
    qt_metacall(QMetaObject::InvokeMetaMethod, 32, _a);
    return qax_result;
}

inline QString _DKHOpenAPI::GetMasterLastPrice(const QString& sTrCode)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sTrCode};
    qt_metacall(QMetaObject::InvokeMetaMethod, 33, _a);
    return qax_result;
}

inline int _DKHOpenAPI::GetMasterListedStockCnt(const QString& sTrCode)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sTrCode};
    qt_metacall(QMetaObject::InvokeMetaMethod, 34, _a);
    return qax_result;
}

inline QString _DKHOpenAPI::GetMasterListedStockDate(const QString& sTrCode)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sTrCode};
    qt_metacall(QMetaObject::InvokeMetaMethod, 35, _a);
    return qax_result;
}

inline QString _DKHOpenAPI::GetMasterStockState(const QString& sTrCode)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sTrCode};
    qt_metacall(QMetaObject::InvokeMetaMethod, 36, _a);
    return qax_result;
}

inline QString _DKHOpenAPI::GetMonthList()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 37, _a);
    return qax_result;
}

inline QString _DKHOpenAPI::GetOptionATM()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 38, _a);
    return qax_result;
}

inline QString _DKHOpenAPI::GetOptionCode(const QString& strActPrice, int nCp, const QString& strMonth)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&strActPrice, (void*)&nCp, (void*)&strMonth};
    qt_metacall(QMetaObject::InvokeMetaMethod, 39, _a);
    return qax_result;
}

inline QString _DKHOpenAPI::GetOptionCodeByActPrice(const QString& sTrCode, int nCp, int nTick)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sTrCode, (void*)&nCp, (void*)&nTick};
    qt_metacall(QMetaObject::InvokeMetaMethod, 40, _a);
    return qax_result;
}

inline QString _DKHOpenAPI::GetOptionCodeByMonth(const QString& sTrCode, int nCp, const QString& strMonth)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sTrCode, (void*)&nCp, (void*)&strMonth};
    qt_metacall(QMetaObject::InvokeMetaMethod, 41, _a);
    return qax_result;
}

inline QString _DKHOpenAPI::GetOutputValue(const QString& strRecordName, int nRepeatIdx, int nItemIdx)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&strRecordName, (void*)&nRepeatIdx, (void*)&nItemIdx};
    qt_metacall(QMetaObject::InvokeMetaMethod, 42, _a);
    return qax_result;
}

inline int _DKHOpenAPI::GetRepeatCnt(const QString& sTrCode, const QString& sRecordName)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sTrCode, (void*)&sRecordName};
    qt_metacall(QMetaObject::InvokeMetaMethod, 43, _a);
    return qax_result;
}

inline QString _DKHOpenAPI::GetSActPriceList(const QString& strBaseAssetGb)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&strBaseAssetGb};
    qt_metacall(QMetaObject::InvokeMetaMethod, 44, _a);
    return qax_result;
}

inline QString _DKHOpenAPI::GetSFOBasisAssetList()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 45, _a);
    return qax_result;
}

inline QString _DKHOpenAPI::GetSFutureCodeByIndex(const QString& strBaseAssetCode, int nIndex)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&strBaseAssetCode, (void*)&nIndex};
    qt_metacall(QMetaObject::InvokeMetaMethod, 46, _a);
    return qax_result;
}

inline QString _DKHOpenAPI::GetSFutureList(const QString& strBaseAssetCode)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&strBaseAssetCode};
    qt_metacall(QMetaObject::InvokeMetaMethod, 47, _a);
    return qax_result;
}

inline QString _DKHOpenAPI::GetSMonthList(const QString& strBaseAssetGb)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&strBaseAssetGb};
    qt_metacall(QMetaObject::InvokeMetaMethod, 48, _a);
    return qax_result;
}

inline QString _DKHOpenAPI::GetSOptionATM(const QString& strBaseAssetGb)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&strBaseAssetGb};
    qt_metacall(QMetaObject::InvokeMetaMethod, 49, _a);
    return qax_result;
}

inline QString _DKHOpenAPI::GetSOptionCode(const QString& strBaseAssetGb, const QString& strActPrice, int nCp, const QString& strMonth)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&strBaseAssetGb, (void*)&strActPrice, (void*)&nCp, (void*)&strMonth};
    qt_metacall(QMetaObject::InvokeMetaMethod, 50, _a);
    return qax_result;
}

inline QString _DKHOpenAPI::GetSOptionCodeByActPrice(const QString& strBaseAssetGb, const QString& sTrCode, int nCp, int nTick)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&strBaseAssetGb, (void*)&sTrCode, (void*)&nCp, (void*)&nTick};
    qt_metacall(QMetaObject::InvokeMetaMethod, 51, _a);
    return qax_result;
}

inline QString _DKHOpenAPI::GetSOptionCodeByMonth(const QString& strBaseAssetGb, const QString& sTrCode, int nCp, const QString& strMonth)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&strBaseAssetGb, (void*)&sTrCode, (void*)&nCp, (void*)&strMonth};
    qt_metacall(QMetaObject::InvokeMetaMethod, 52, _a);
    return qax_result;
}

inline QString _DKHOpenAPI::GetThemeGroupCode(const QString& strThemeCode)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&strThemeCode};
    qt_metacall(QMetaObject::InvokeMetaMethod, 53, _a);
    return qax_result;
}

inline QString _DKHOpenAPI::GetThemeGroupList(int nType)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&nType};
    qt_metacall(QMetaObject::InvokeMetaMethod, 54, _a);
    return qax_result;
}

inline QString _DKHOpenAPI::KOA_Functions(const QString& sFunctionName, const QString& sParam)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sFunctionName, (void*)&sParam};
    qt_metacall(QMetaObject::InvokeMetaMethod, 55, _a);
    return qax_result;
}

inline int _DKHOpenAPI::SendCondition(const QString& strScrNo, const QString& strConditionName, int nIndex, int nSearch)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&strScrNo, (void*)&strConditionName, (void*)&nIndex, (void*)&nSearch};
    qt_metacall(QMetaObject::InvokeMetaMethod, 56, _a);
    return qax_result;
}

inline void _DKHOpenAPI::SendConditionStop(const QString& strScrNo, const QString& strConditionName, int nIndex)
{
    void *_a[] = {0, (void*)&strScrNo, (void*)&strConditionName, (void*)&nIndex};
    qt_metacall(QMetaObject::InvokeMetaMethod, 57, _a);
}

inline int _DKHOpenAPI::SendOrder(const QString& sRQName, const QString& sScreenNo, const QString& sAccNo, int nOrderType, const QString& sCode, int nQty, int nPrice, const QString& sHogaGb, const QString& sOrgOrderNo)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sRQName, (void*)&sScreenNo, (void*)&sAccNo, (void*)&nOrderType, (void*)&sCode, (void*)&nQty, (void*)&nPrice, (void*)&sHogaGb, (void*)&sOrgOrderNo};
    qt_metacall(QMetaObject::InvokeMetaMethod, 58, _a);
    return qax_result;
}

inline int _DKHOpenAPI::SendOrderCredit(const QString& sRQName, const QString& sScreenNo, const QString& sAccNo, int nOrderType, const QString& sCode, int nQty, int nPrice, const QString& sHogaGb, const QString& sCreditGb, const QString& sLoanDate, const QString& sOrgOrderNo)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sRQName, (void*)&sScreenNo, (void*)&sAccNo, (void*)&nOrderType, (void*)&sCode, (void*)&nQty, (void*)&nPrice, (void*)&sHogaGb, (void*)&sCreditGb, (void*)&sLoanDate, (void*)&sOrgOrderNo};
    qt_metacall(QMetaObject::InvokeMetaMethod, 59, _a);
    return qax_result;
}

inline int _DKHOpenAPI::SendOrderFO(const QString& sRQName, const QString& sScreenNo, const QString& sAccNo, const QString& sCode, int lOrdKind, const QString& sSlbyTp, const QString& sOrdTp, int lQty, const QString& sPrice, const QString& sOrgOrdNo)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sRQName, (void*)&sScreenNo, (void*)&sAccNo, (void*)&sCode, (void*)&lOrdKind, (void*)&sSlbyTp, (void*)&sOrdTp, (void*)&lQty, (void*)&sPrice, (void*)&sOrgOrdNo};
    qt_metacall(QMetaObject::InvokeMetaMethod, 60, _a);
    return qax_result;
}

inline int _DKHOpenAPI::SetInfoData(const QString& sInfoData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sInfoData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 61, _a);
    return qax_result;
}

inline void _DKHOpenAPI::SetInputValue(const QString& sID, const QString& sValue)
{
    void *_a[] = {0, (void*)&sID, (void*)&sValue};
    qt_metacall(QMetaObject::InvokeMetaMethod, 62, _a);
}

inline int _DKHOpenAPI::SetOutputFID(const QString& sID)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sID};
    qt_metacall(QMetaObject::InvokeMetaMethod, 63, _a);
    return qax_result;
}

inline int _DKHOpenAPI::SetRealReg(const QString& strScreenNo, const QString& strCodeList, const QString& strFidList, const QString& strOptType)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&strScreenNo, (void*)&strCodeList, (void*)&strFidList, (void*)&strOptType};
    qt_metacall(QMetaObject::InvokeMetaMethod, 64, _a);
    return qax_result;
}

inline void _DKHOpenAPI::SetRealRemove(const QString& strScrNo, const QString& strDelCode)
{
    void *_a[] = {0, (void*)&strScrNo, (void*)&strDelCode};
    qt_metacall(QMetaObject::InvokeMetaMethod, 65, _a);
}


inline int KHOpenAPI::CommConnect()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 44, _a);
    return qax_result;
}

inline QString KHOpenAPI::CommGetData(const QString& sJongmokCode, const QString& sRealType, const QString& sFieldName, int nIndex, const QString& sInnerFieldName)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sJongmokCode, (void*)&sRealType, (void*)&sFieldName, (void*)&nIndex, (void*)&sInnerFieldName};
    qt_metacall(QMetaObject::InvokeMetaMethod, 45, _a);
    return qax_result;
}

inline int KHOpenAPI::CommInvestRqData(const QString& sMarketGb, const QString& sRQName, const QString& sScreenNo)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sMarketGb, (void*)&sRQName, (void*)&sScreenNo};
    qt_metacall(QMetaObject::InvokeMetaMethod, 46, _a);
    return qax_result;
}

inline int KHOpenAPI::CommKwRqData(const QString& sArrCode, int bNext, int nCodeCount, int nTypeFlag, const QString& sRQName, const QString& sScreenNo)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sArrCode, (void*)&bNext, (void*)&nCodeCount, (void*)&nTypeFlag, (void*)&sRQName, (void*)&sScreenNo};
    qt_metacall(QMetaObject::InvokeMetaMethod, 47, _a);
    return qax_result;
}

inline int KHOpenAPI::CommRqData(const QString& sRQName, const QString& sTrCode, int nPrevNext, const QString& sScreenNo)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sRQName, (void*)&sTrCode, (void*)&nPrevNext, (void*)&sScreenNo};
    qt_metacall(QMetaObject::InvokeMetaMethod, 48, _a);
    return qax_result;
}

inline void KHOpenAPI::CommTerminate()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 49, _a);
}

inline void KHOpenAPI::DisconnectRealData(const QString& sScnNo)
{
    void *_a[] = {0, (void*)&sScnNo};
    qt_metacall(QMetaObject::InvokeMetaMethod, 50, _a);
}

inline QString KHOpenAPI::GetAPIModulePath()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 51, _a);
    return qax_result;
}

inline QString KHOpenAPI::GetActPriceList()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 52, _a);
    return qax_result;
}

inline QString KHOpenAPI::GetBranchCodeName()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 53, _a);
    return qax_result;
}

inline QString KHOpenAPI::GetChejanData(int nFid)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&nFid};
    qt_metacall(QMetaObject::InvokeMetaMethod, 54, _a);
    return qax_result;
}

inline QString KHOpenAPI::GetCodeListByMarket(const QString& sMarket)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sMarket};
    qt_metacall(QMetaObject::InvokeMetaMethod, 55, _a);
    return qax_result;
}

inline QString KHOpenAPI::GetCommData(const QString& strTrCode, const QString& strRecordName, int nIndex, const QString& strItemName)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&strTrCode, (void*)&strRecordName, (void*)&nIndex, (void*)&strItemName};
    qt_metacall(QMetaObject::InvokeMetaMethod, 56, _a);
    return qax_result;
}

inline QVariant KHOpenAPI::GetCommDataEx(const QString& strTrCode, const QString& strRecordName)
{
    QVariant qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&strTrCode, (void*)&strRecordName};
    qt_metacall(QMetaObject::InvokeMetaMethod, 57, _a);
    return qax_result;
}

inline QString KHOpenAPI::GetCommRealData(const QString& sTrCode, int nFid)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sTrCode, (void*)&nFid};
    qt_metacall(QMetaObject::InvokeMetaMethod, 58, _a);
    return qax_result;
}

inline int KHOpenAPI::GetConditionLoad()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 59, _a);
    return qax_result;
}

inline QString KHOpenAPI::GetConditionNameList()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 60, _a);
    return qax_result;
}

inline int KHOpenAPI::GetConnectState()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 61, _a);
    return qax_result;
}

inline int KHOpenAPI::GetDataCount(const QString& strRecordName)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&strRecordName};
    qt_metacall(QMetaObject::InvokeMetaMethod, 62, _a);
    return qax_result;
}

inline QString KHOpenAPI::GetFutureCodeByIndex(int nIndex)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&nIndex};
    qt_metacall(QMetaObject::InvokeMetaMethod, 63, _a);
    return qax_result;
}

inline QString KHOpenAPI::GetFutureList()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 64, _a);
    return qax_result;
}

inline QString KHOpenAPI::GetLoginInfo(const QString& sTag)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sTag};
    qt_metacall(QMetaObject::InvokeMetaMethod, 65, _a);
    return qax_result;
}

inline int KHOpenAPI::GetMarketType(const QString& sTrCode)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sTrCode};
    qt_metacall(QMetaObject::InvokeMetaMethod, 66, _a);
    return qax_result;
}

inline QString KHOpenAPI::GetMasterCodeName(const QString& sTrCode)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sTrCode};
    qt_metacall(QMetaObject::InvokeMetaMethod, 67, _a);
    return qax_result;
}

inline QString KHOpenAPI::GetMasterConstruction(const QString& sTrCode)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sTrCode};
    qt_metacall(QMetaObject::InvokeMetaMethod, 68, _a);
    return qax_result;
}

inline QString KHOpenAPI::GetMasterLastPrice(const QString& sTrCode)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sTrCode};
    qt_metacall(QMetaObject::InvokeMetaMethod, 69, _a);
    return qax_result;
}

inline int KHOpenAPI::GetMasterListedStockCnt(const QString& sTrCode)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sTrCode};
    qt_metacall(QMetaObject::InvokeMetaMethod, 70, _a);
    return qax_result;
}

inline QString KHOpenAPI::GetMasterListedStockDate(const QString& sTrCode)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sTrCode};
    qt_metacall(QMetaObject::InvokeMetaMethod, 71, _a);
    return qax_result;
}

inline QString KHOpenAPI::GetMasterStockState(const QString& sTrCode)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sTrCode};
    qt_metacall(QMetaObject::InvokeMetaMethod, 72, _a);
    return qax_result;
}

inline QString KHOpenAPI::GetMonthList()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 73, _a);
    return qax_result;
}

inline QString KHOpenAPI::GetOptionATM()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 74, _a);
    return qax_result;
}

inline QString KHOpenAPI::GetOptionCode(const QString& strActPrice, int nCp, const QString& strMonth)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&strActPrice, (void*)&nCp, (void*)&strMonth};
    qt_metacall(QMetaObject::InvokeMetaMethod, 75, _a);
    return qax_result;
}

inline QString KHOpenAPI::GetOptionCodeByActPrice(const QString& sTrCode, int nCp, int nTick)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sTrCode, (void*)&nCp, (void*)&nTick};
    qt_metacall(QMetaObject::InvokeMetaMethod, 76, _a);
    return qax_result;
}

inline QString KHOpenAPI::GetOptionCodeByMonth(const QString& sTrCode, int nCp, const QString& strMonth)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sTrCode, (void*)&nCp, (void*)&strMonth};
    qt_metacall(QMetaObject::InvokeMetaMethod, 77, _a);
    return qax_result;
}

inline QString KHOpenAPI::GetOutputValue(const QString& strRecordName, int nRepeatIdx, int nItemIdx)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&strRecordName, (void*)&nRepeatIdx, (void*)&nItemIdx};
    qt_metacall(QMetaObject::InvokeMetaMethod, 78, _a);
    return qax_result;
}

inline int KHOpenAPI::GetRepeatCnt(const QString& sTrCode, const QString& sRecordName)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sTrCode, (void*)&sRecordName};
    qt_metacall(QMetaObject::InvokeMetaMethod, 79, _a);
    return qax_result;
}

inline QString KHOpenAPI::GetSActPriceList(const QString& strBaseAssetGb)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&strBaseAssetGb};
    qt_metacall(QMetaObject::InvokeMetaMethod, 80, _a);
    return qax_result;
}

inline QString KHOpenAPI::GetSFOBasisAssetList()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 81, _a);
    return qax_result;
}

inline QString KHOpenAPI::GetSFutureCodeByIndex(const QString& strBaseAssetCode, int nIndex)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&strBaseAssetCode, (void*)&nIndex};
    qt_metacall(QMetaObject::InvokeMetaMethod, 82, _a);
    return qax_result;
}

inline QString KHOpenAPI::GetSFutureList(const QString& strBaseAssetCode)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&strBaseAssetCode};
    qt_metacall(QMetaObject::InvokeMetaMethod, 83, _a);
    return qax_result;
}

inline QString KHOpenAPI::GetSMonthList(const QString& strBaseAssetGb)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&strBaseAssetGb};
    qt_metacall(QMetaObject::InvokeMetaMethod, 84, _a);
    return qax_result;
}

inline QString KHOpenAPI::GetSOptionATM(const QString& strBaseAssetGb)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&strBaseAssetGb};
    qt_metacall(QMetaObject::InvokeMetaMethod, 85, _a);
    return qax_result;
}

inline QString KHOpenAPI::GetSOptionCode(const QString& strBaseAssetGb, const QString& strActPrice, int nCp, const QString& strMonth)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&strBaseAssetGb, (void*)&strActPrice, (void*)&nCp, (void*)&strMonth};
    qt_metacall(QMetaObject::InvokeMetaMethod, 86, _a);
    return qax_result;
}

inline QString KHOpenAPI::GetSOptionCodeByActPrice(const QString& strBaseAssetGb, const QString& sTrCode, int nCp, int nTick)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&strBaseAssetGb, (void*)&sTrCode, (void*)&nCp, (void*)&nTick};
    qt_metacall(QMetaObject::InvokeMetaMethod, 87, _a);
    return qax_result;
}

inline QString KHOpenAPI::GetSOptionCodeByMonth(const QString& strBaseAssetGb, const QString& sTrCode, int nCp, const QString& strMonth)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&strBaseAssetGb, (void*)&sTrCode, (void*)&nCp, (void*)&strMonth};
    qt_metacall(QMetaObject::InvokeMetaMethod, 88, _a);
    return qax_result;
}

inline QString KHOpenAPI::GetThemeGroupCode(const QString& strThemeCode)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&strThemeCode};
    qt_metacall(QMetaObject::InvokeMetaMethod, 89, _a);
    return qax_result;
}

inline QString KHOpenAPI::GetThemeGroupList(int nType)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&nType};
    qt_metacall(QMetaObject::InvokeMetaMethod, 90, _a);
    return qax_result;
}

inline QString KHOpenAPI::KOA_Functions(const QString& sFunctionName, const QString& sParam)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sFunctionName, (void*)&sParam};
    qt_metacall(QMetaObject::InvokeMetaMethod, 91, _a);
    return qax_result;
}

inline int KHOpenAPI::SendCondition(const QString& strScrNo, const QString& strConditionName, int nIndex, int nSearch)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&strScrNo, (void*)&strConditionName, (void*)&nIndex, (void*)&nSearch};
    qt_metacall(QMetaObject::InvokeMetaMethod, 92, _a);
    return qax_result;
}

inline void KHOpenAPI::SendConditionStop(const QString& strScrNo, const QString& strConditionName, int nIndex)
{
    void *_a[] = {0, (void*)&strScrNo, (void*)&strConditionName, (void*)&nIndex};
    qt_metacall(QMetaObject::InvokeMetaMethod, 93, _a);
}

inline int KHOpenAPI::SendOrder(const QString& sRQName, const QString& sScreenNo, const QString& sAccNo, int nOrderType, const QString& sCode, int nQty, int nPrice, const QString& sHogaGb, const QString& sOrgOrderNo)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sRQName, (void*)&sScreenNo, (void*)&sAccNo, (void*)&nOrderType, (void*)&sCode, (void*)&nQty, (void*)&nPrice, (void*)&sHogaGb, (void*)&sOrgOrderNo};
    qt_metacall(QMetaObject::InvokeMetaMethod, 94, _a);
    return qax_result;
}

inline int KHOpenAPI::SendOrderCredit(const QString& sRQName, const QString& sScreenNo, const QString& sAccNo, int nOrderType, const QString& sCode, int nQty, int nPrice, const QString& sHogaGb, const QString& sCreditGb, const QString& sLoanDate, const QString& sOrgOrderNo)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sRQName, (void*)&sScreenNo, (void*)&sAccNo, (void*)&nOrderType, (void*)&sCode, (void*)&nQty, (void*)&nPrice, (void*)&sHogaGb, (void*)&sCreditGb, (void*)&sLoanDate, (void*)&sOrgOrderNo};
    qt_metacall(QMetaObject::InvokeMetaMethod, 95, _a);
    return qax_result;
}

inline int KHOpenAPI::SendOrderFO(const QString& sRQName, const QString& sScreenNo, const QString& sAccNo, const QString& sCode, int lOrdKind, const QString& sSlbyTp, const QString& sOrdTp, int lQty, const QString& sPrice, const QString& sOrgOrdNo)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sRQName, (void*)&sScreenNo, (void*)&sAccNo, (void*)&sCode, (void*)&lOrdKind, (void*)&sSlbyTp, (void*)&sOrdTp, (void*)&lQty, (void*)&sPrice, (void*)&sOrgOrdNo};
    qt_metacall(QMetaObject::InvokeMetaMethod, 96, _a);
    return qax_result;
}

inline int KHOpenAPI::SetInfoData(const QString& sInfoData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sInfoData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 97, _a);
    return qax_result;
}

inline void KHOpenAPI::SetInputValue(const QString& sID, const QString& sValue)
{
    void *_a[] = {0, (void*)&sID, (void*)&sValue};
    qt_metacall(QMetaObject::InvokeMetaMethod, 98, _a);
}

inline int KHOpenAPI::SetOutputFID(const QString& sID)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sID};
    qt_metacall(QMetaObject::InvokeMetaMethod, 99, _a);
    return qax_result;
}

inline int KHOpenAPI::SetRealReg(const QString& strScreenNo, const QString& strCodeList, const QString& strFidList, const QString& strOptType)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&strScreenNo, (void*)&strCodeList, (void*)&strFidList, (void*)&strOptType};
    qt_metacall(QMetaObject::InvokeMetaMethod, 100, _a);
    return qax_result;
}

inline void KHOpenAPI::SetRealRemove(const QString& strScrNo, const QString& strDelCode)
{
    void *_a[] = {0, (void*)&strScrNo, (void*)&strDelCode};
    qt_metacall(QMetaObject::InvokeMetaMethod, 101, _a);
}



#endif

}

QT_BEGIN_NAMESPACE

namespace QtMetaTypePrivate {
template<>
struct QMetaTypeFunctionHelper<KHOpenAPILib::_DKHOpenAPI, /* Accepted */ true> {
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<KHOpenAPILib::_DKHOpenAPI*>(t)->KHOpenAPILib::_DKHOpenAPI::~_DKHOpenAPI();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) KHOpenAPILib::_DKHOpenAPI;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const KHOpenAPILib::_DKHOpenAPI*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<KHOpenAPILib::_DKHOpenAPI*>(t); }
#endif // QT_NO_DATASTREAM
};

template<>
struct QMetaTypeFunctionHelper<KHOpenAPILib::KHOpenAPI, /* Accepted */ true> {
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<KHOpenAPILib::KHOpenAPI*>(t)->KHOpenAPILib::KHOpenAPI::~KHOpenAPI();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) KHOpenAPILib::KHOpenAPI;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const KHOpenAPILib::KHOpenAPI*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<KHOpenAPILib::KHOpenAPI*>(t); }
#endif // QT_NO_DATASTREAM
};

} // namespace QtMetaTypePrivate
QT_END_NAMESPACE

#endif

