// Created by cgo -godefs - DO NOT EDIT
// cgo -godefs D:\Go\src\github.com\ghts\ghts\api\nh\internal\g_ctype_orig.go

package internal

type AccountInfo struct {
	AccountNo		[11]byte
	AccountName		[40]byte
	AccountProductCode	[3]byte
	AmnTabCode		[4]byte
	ExpirationDate		[8]byte
	Granted			byte
	Filler			[189]byte
}
type LoginInfo struct {
	Date		[14]byte
	ServerName	[15]byte
	UserID		[8]byte
	AccountCount	[3]byte
	Accountlist	[999]AccountInfo
}
type LoginBlock struct {
	TrIdNo		int32
	LoginInfo	*LoginInfo
}

type MsgHeader struct {
	MsgCode	[5]byte
	UsrMsg	[80]byte
}

type Received struct {
	BlockName	*byte
	DataString	*byte
	Length		int32
}
type OutDataBlock struct {
	TrIdNo		int32
	DataStruct	*Received
}

type Tc1101InBlock struct {
	Lang	[1]byte
	X_Lang	byte
	Code	[6]byte
	X_Code	byte
}
type Tc1101OutBlock struct {
	Code			[6]byte
	X_Code			byte
	Title			[13]byte
	X_Title			byte
	MarketPrice		[7]byte
	X_MarketPrice		byte
	DiffSign		[1]byte
	X_DiffSign		byte
	Diff			[6]byte
	X_Diff			byte
	DiffRate		[5]byte
	X_DiffRate		byte
	OfferPrice		[7]byte
	X_OfferPrice		byte
	BidPrice		[7]byte
	X_BidPrice		byte
	Volume			[9]byte
	X_Volume		byte
	TrVolRate		[6]byte
	X_TrVolRate		byte
	FloatRate		[5]byte
	X_FloatRate		byte
	TrAmount		[9]byte
	X_TrAmount		byte
	UpLmtPrice		[7]byte
	X_UpLmtPrice		byte
	High			[7]byte
	X_High			byte
	Open			[7]byte
	X_Open			byte
	VsOpenSign		[1]byte
	X_VsOpenSign		byte
	VsOpenDiff		[6]byte
	X_VsOpenDiff		byte
	Low			[7]byte
	X_Low			byte
	LowLmtPrice		[7]byte
	X_LowLmtPrice		byte
	Time			[8]byte
	X_Time			byte
	OfferPrice1		[7]byte
	X_OfferPrice1		byte
	OfferPrice2		[7]byte
	X_OfferPrice2		byte
	OfferPrice3		[7]byte
	X_OfferPrice3		byte
	OfferPrice4		[7]byte
	X_OfferPrice4		byte
	OfferPrice5		[7]byte
	X_OfferPrice5		byte
	OfferPrice6		[7]byte
	X_OfferPrice6		byte
	OfferPrice7		[7]byte
	X_OfferPrice7		byte
	OfferPrice8		[7]byte
	X_OfferPrice8		byte
	OfferPrice9		[7]byte
	X_OfferPrice9		byte
	OfferPrice10		[7]byte
	X_OfferPrice10		byte
	BidPrice1		[7]byte
	X_BidPrice1		byte
	BidPrice2		[7]byte
	X_BidPrice2		byte
	BidPrice3		[7]byte
	X_BidPrice3		byte
	BidPrice4		[7]byte
	X_BidPrice4		byte
	BidPrice5		[7]byte
	X_BidPrice5		byte
	BidPrice6		[7]byte
	X_BidPrice6		byte
	BidPrice7		[7]byte
	X_BidPrice7		byte
	BidPrice8		[7]byte
	X_BidPrice8		byte
	BidPrice9		[7]byte
	X_BidPrice9		byte
	BidPrice10		[7]byte
	X_BidPrice10		byte
	OfferVolume1		[9]byte
	X_OfferVolume1		byte
	OfferVolume2		[9]byte
	X_OfferVolume2		byte
	OfferVolume3		[9]byte
	X_OfferVolume3		byte
	OfferVolume4		[9]byte
	X_OfferVolume4		byte
	OfferVolume5		[9]byte
	X_OfferVolume5		byte
	OfferVolume6		[9]byte
	X_OfferVolume6		byte
	OfferVolume7		[9]byte
	X_OfferVolume7		byte
	OfferVolume8		[9]byte
	X_OfferVolume8		byte
	OfferVolume9		[9]byte
	X_OfferVolume9		byte
	OfferVolume10		[9]byte
	X_OfferVolume10		byte
	BidVolume1		[9]byte
	X_BidVolume1		byte
	BidVolume2		[9]byte
	X_BidVolume2		byte
	BidVolume3		[9]byte
	X_BidVolume3		byte
	BidVolume4		[9]byte
	X_BidVolume4		byte
	BidVolume5		[9]byte
	X_BidVolume5		byte
	BidVolume6		[9]byte
	X_BidVolume6		byte
	BidVolume7		[9]byte
	X_BidVolume7		byte
	BidVolume8		[9]byte
	X_BidVolume8		byte
	BidVolume9		[9]byte
	X_BidVolume9		byte
	BidVolume10		[9]byte
	X_BidVolume10		byte
	OfferVolTot		[9]byte
	X_OfferVolTot		byte
	BidVolTot		[9]byte
	X_BidVolTot		byte
	OfferVolAfterHour	[9]byte
	X_OfferVolAfterHour	byte
	BidVolAfterHour		[9]byte
	X_BidVolAfterHour	byte
	PivotUp2		[7]byte
	X_PivotUp2		byte
	PivotUp1		[7]byte
	X_PivotUp1		byte
	PivotPrice		[7]byte
	X_PivotPrice		byte
	PivotDown1		[7]byte
	X_PivotDown1		byte
	PivotDown2		[7]byte
	X_PivotDown2		byte
	Market			[6]byte
	X_Market		byte
	Sector			[18]byte
	X_Sector		byte
	CapSize			[6]byte
	X_CapSize		byte
	SettleMonth		[16]byte
	X_SettleMonth		byte
	MarketAction1		[16]byte
	X_MarketAction1		byte
	MarketAction2		[16]byte
	X_MarketAction2		byte
	MarketAction3		[16]byte
	X_MarketAction3		byte
	MarketAction4		[16]byte
	X_MarketAction4		byte
	MarketAction5		[16]byte
	X_MarketAction5		byte
	MarketAction6		[16]byte
	X_MarketAction6		byte
	CircuitBreaker		[6]byte
	X_CircuitBreaker	byte
	NominalPrice		[7]byte
	X_NominalPrice		byte
	PrevPriceTitle		[12]byte
	X_PrevPriceTitle	byte
	PrevPrice		[7]byte
	X_PrevPrice		byte
	MortgageValue		[7]byte
	X_MortgageValue		byte
	PublicOfferPrice	[7]byte
	X_PublicOfferPrice	byte
	High5Day		[7]byte
	X_High5Day		byte
	Low5Day			[7]byte
	X_Low5Day		byte
	High20Day		[7]byte
	X_High20Day		byte
	Low20Day		[7]byte
	X_Low20Day		byte
	High1Year		[7]byte
	X_High1Year		byte
	High1YearDate		[4]byte
	X_High1YearDate		byte
	Low1Year		[7]byte
	X_Low1Year		byte
	Low1YearDate		[4]byte
	X_Low1YearDate		byte
	FloatVolume		[8]byte
	X_FloatVolume		byte
	ListVolBy1000		[12]byte
	X_ListVolBy1000		byte
	MarketCapital		[9]byte
	X_MarketCapital		byte
	TraderInfoTime		[5]byte
	X_TraderInfoTime	byte
	Seller1			[6]byte
	X_Seller1		byte
	Buyer1			[6]byte
	X_Buyer1		byte
	Seller1Volume		[9]byte
	X_Seller1Volume		byte
	Buyer1Volume		[9]byte
	X_Buyer1Volume		byte
	Seller2			[6]byte
	X_Seller2		byte
	Buyer2			[6]byte
	X_Buyer2		byte
	Seller2Volume		[9]byte
	X_Seller2Volume		byte
	Buyer2Volume		[9]byte
	X_Buyer2Volume		byte
	Seller3			[6]byte
	X_Seller3		byte
	Buyer3			[6]byte
	X_Buyer3		byte
	Seller3Volume		[9]byte
	X_Seller3Volume		byte
	Buyer3Volume		[9]byte
	X_Buyer3Volume		byte
	Seller4			[6]byte
	X_Seller4		byte
	Buyer4			[6]byte
	X_Buyer4		byte
	Seller4Volume		[9]byte
	X_Seller4Volume		byte
	Buyer4Volume		[9]byte
	X_Buyer4Volume		byte
	Seller5			[6]byte
	X_Seller5		byte
	Buyer5			[6]byte
	X_Buyer5		byte
	Seller5Volume		[9]byte
	X_Seller5Volume		byte
	Buyer5Volume		[9]byte
	X_Buyer5Volume		byte
	ForeignSellVolume	[9]byte
	X_ForeignSellVolume	byte
	ForeignBuyVolume	[9]byte
	X_ForeignBuyVolume	byte
	ForeignTime		[6]byte
	X_ForeignTime		byte
	ForeignHoldingRate	[5]byte
	X_ForeignHoldingRate	byte
	SettleDate		[4]byte
	X_SettleDate		byte
	DebtPercent		[5]byte
	X_DebtPercent		byte
	RightsIssueDate		[4]byte
	X_RightsIssueDate	byte
	BonusIssueDate		[4]byte
	X_BonusIssueDate	byte
	RightsIssueRate		[5]byte
	X_RightsIssueRate	byte
	BonusIssueRate		[5]byte
	X_BonusIssueRate	byte
	ForeignFloatVol		[10]byte
	X_ForeignFloatVol	byte
	TreasuryStock		[1]byte
	X_TreasuryStock		byte
	IpoDate			[8]byte
	X_IpoDate		byte
	MajorHoldRate		[5]byte
	X_MajorHoldRate		byte
	MajorHoldInfoDate	[6]byte
	X_MajorHoldInfoDate	byte
	FourLeafClover		[1]byte
	X_FourLeafClover	byte
	MarginRate		[1]byte
	X_MarginRate		byte
	Capital			[9]byte
	X_Capital		byte
	SellTotalSum		[9]byte
	X_SellTotalSum		byte
	BuyTotalSum		[9]byte
	X_BuyTotalSum		byte
	Title2			[21]byte
	X_Title2		byte
	BackdoorListing		[1]byte
	X_BackdoorListing	byte
	FloatRate2		[6]byte
	X_FloatRate2		byte
	Market2			[6]byte
	X_Market2		byte
	DebtTrDate		[4]byte
	X_DebtTrDate		byte
	DebtTrPercent		[5]byte
	X_DebtTrPercent		byte
	PER			[5]byte
	X_PER			byte
	DebtLimit		[1]byte
	X_DebtLimit		byte
	WeightAvgPrice		[7]byte
	X_WeightAvgPrice	byte
	ListedVolume		[12]byte
	X_ListedVolume		byte
	AddListing		[12]byte
	X_AddListing		byte
	Comment			[100]byte
	X_Comment		byte
	PrevVolume		[9]byte
	X_PrevVolume		byte
	VsPrevSign		[1]byte
	X_VsPrevSign		byte
	VsPrevDiff		[6]byte
	X_VsPrevDiff		byte
	High1Year2		[7]byte
	X_High1Year2		byte
	High1YearDate2		[4]byte
	X_High1YearDate2	byte
	Low1Year2		[7]byte
	X_Low1Year2		byte
	Low1YearDate2		[4]byte
	X_Low1YearDate2		byte
	ForeignHoldQty		[15]byte
	X_ForeignHoldQty	byte
	ForeignLmtPercent	[5]byte
	X_ForeignLmtPercent	byte
	TrUnitVolume		[5]byte
	X_TrUnitVolume		byte
	DarkPoolOfferBid	[1]byte
	X_DarkPoolOfferBid	byte
	DarkPoolExist		[1]byte
	X_DarkPoolExist		byte
}
type Tc1101OutBlock2 struct {
	Time		[8]byte
	X_Time		byte
	MarketPrice	[7]byte
	X_MarketPrice	byte
	DiffSign	[1]byte
	X_DiffSign	byte
	Diff		[6]byte
	X_Diff		byte
	OfferPrice	[7]byte
	X_OfferPrice	byte
	BidPrice	[7]byte
	X_BidPrice	byte
	DiffVolume	[8]byte
	X_DiffVolume	byte
	Volume		[9]byte
	X_Volume	byte
}
type Tc1101OutBlock3 struct {
	SyncOfferBid		[1]byte
	X_SyncOfferBid		byte
	EstmPrice		[7]byte
	X_EstmPrice		byte
	EstmSign		[1]byte
	X_EstmSign		byte
	EstmDiff		[6]byte
	X_EstmDiff		byte
	EstmDiffRate		[5]byte
	X_EstmDiffRate		byte
	EstmVol			[9]byte
	X_EstmVol		byte
	ECN_InfoExist		[1]byte
	X_ECN_InfoExist		byte
	ECN_PrevPrice		[9]byte
	X_ECN_PrevPrice		byte
	ECN_DiffSign		[1]byte
	X_ECN_DiffSign		byte
	ECN_Diff		[9]byte
	X_ECN_Diff		byte
	ECN_DiffRate		[5]byte
	X_ECN_DiffRate		byte
	ECN_Volume		[10]byte
	X_ECN_Volume		byte
	VsECN_EstmSign		[1]byte
	X_VsECN_EstmSign	byte
	VsECN_EstmDiff		[6]byte
	X_VsECN_EstmDiff	byte
	VsECN_EstmDiffRate	[5]byte
	X_ECN_EstmDiffRate	byte
}
type Tc1101 struct {
	C1101InBlock	Tc1101InBlock
	C1101OutBlock	Tc1101OutBlock
	C1101OutBlock2	[20]Tc1101OutBlock2
	C1101OutBlock3	Tc1101OutBlock3
}

type Tc1151InBlock struct {
	Lang	[1]byte
	X_Lang	byte
	Code	[6]byte
	X_Code	byte
}
type Tc1151OutBlock struct {
	Code			[6]byte
	X_Code			byte
	Title			[13]byte
	X_Title			byte
	MarketPrice		[7]byte
	X_MarketPrice		byte
	DiffSign		[1]byte
	X_DiffSign		byte
	Diff			[6]byte
	X_Diff			byte
	DiffRate		[5]byte
	X_DiffRate		byte
	OfferPrice		[7]byte
	X_OfferPrice		byte
	BidPrice		[7]byte
	X_BidPrice		byte
	Volume			[9]byte
	X_Volume		byte
	TrVolRate		[6]byte
	X_TrVolRate		byte
	FloatVolRate		[5]byte
	X_FloatVolRate		byte
	TrAmount		[9]byte
	X_TrAmount		byte
	UpLmtPrice		[7]byte
	X_UpLmtPrice		byte
	High			[7]byte
	X_High			byte
	Open			[7]byte
	X_Open			byte
	VsOpenSign		[1]byte
	X_VsOpenSign		byte
	VsOpenDiff		[6]byte
	X_VsOpenDiff		byte
	Low			[7]byte
	X_Low			byte
	LowLmtPrice		[7]byte
	X_LowLmtPrice		byte
	Time			[8]byte
	X_Time			byte
	OfferPrice1		[7]byte
	X_OfferPrice1		byte
	OfferPrice2		[7]byte
	X_OfferPrice2		byte
	OfferPrice3		[7]byte
	X_OfferPrice3		byte
	OfferPrice4		[7]byte
	X_OfferPrice4		byte
	OfferPrice5		[7]byte
	X_OfferPrice5		byte
	OfferPrice6		[7]byte
	X_OfferPrice6		byte
	OfferPrice7		[7]byte
	X_OfferPrice7		byte
	OfferPrice8		[7]byte
	X_OfferPrice8		byte
	OfferPrice9		[7]byte
	X_OfferPrice9		byte
	OfferPrice10		[7]byte
	X_OfferPrice10		byte
	BidPrice1		[7]byte
	X_BidPrice1		byte
	BidPrice2		[7]byte
	X_BidPrice2		byte
	BidPrice3		[7]byte
	X_BidPrice3		byte
	BidPrice4		[7]byte
	X_BidPrice4		byte
	BidPrice5		[7]byte
	X_BidPrice5		byte
	BidPrice6		[7]byte
	X_BidPrice6		byte
	BidPrice7		[7]byte
	X_BidPrice7		byte
	BidPrice8		[7]byte
	X_BidPrice8		byte
	BidPrice9		[7]byte
	X_BidPrice9		byte
	BidPrice10		[7]byte
	X_BidPrice10		byte
	OfferVolume1		[9]byte
	X_OfferVolume1		byte
	OfferVolume2		[9]byte
	X_OfferVolume2		byte
	OfferVolume3		[9]byte
	X_OfferVolume3		byte
	OfferVolume4		[9]byte
	X_OfferVolume4		byte
	OfferVolume5		[9]byte
	X_OfferVolume5		byte
	OfferVolume6		[9]byte
	X_OfferVolume6		byte
	OfferVolume7		[9]byte
	X_OfferVolume7		byte
	OfferVolume8		[9]byte
	X_OfferVolume8		byte
	OfferVolume9		[9]byte
	X_OfferVolume9		byte
	OfferVolume10		[9]byte
	X_OfferVolume10		byte
	BidVolume1		[9]byte
	X_BidVolume1		byte
	BidVolume2		[9]byte
	X_BidVolume2		byte
	BidVolume3		[9]byte
	X_BidVolume3		byte
	BidVolume4		[9]byte
	X_BidVolume4		byte
	BidVolume5		[9]byte
	X_BidVolume5		byte
	BidVolume6		[9]byte
	X_BidVolume6		byte
	BidVolume7		[9]byte
	X_BidVolume7		byte
	BidVolume8		[9]byte
	X_BidVolume8		byte
	BidVolume9		[9]byte
	X_BidVolume9		byte
	BidVolume10		[9]byte
	X_BidVolume10		byte
	OfferVolTot		[9]byte
	X_OfferVolTot		byte
	BidVolTot		[9]byte
	X_BidVolTot		byte
	OfferVolAfterHour	[9]byte
	X_OfferVolAfterHour	byte
	BidVolAfterHour		[9]byte
	X_BidVolAfterHour	byte
	PivotUp2		[7]byte
	X_PivotUp2		byte
	PivotUp1		[7]byte
	X_PivotUp1		byte
	PivotPrice		[7]byte
	X_PivotPrice		byte
	PivotDown1		[7]byte
	X_PivotDown1		byte
	PivotDown2		[7]byte
	X_PivotDown2		byte
	Market			[6]byte
	X_Market		byte
	Sector			[18]byte
	X_Sector		byte
	CapSize			[6]byte
	X_CapSize		byte
	SettleMonth		[16]byte
	X_SettleMonth		byte
	MarketAction1		[16]byte
	X_MarketAction1		byte
	MarketAction2		[16]byte
	X_MarketAction2		byte
	MarketAction3		[16]byte
	X_MarketAction3		byte
	MarketAction4		[16]byte
	X_MarketAction4		byte
	MarketAction5		[16]byte
	X_MarketAction5		byte
	MarketAction6		[16]byte
	X_MarketAction6		byte
	CircuitBreaker		[6]byte
	X_CircuitBreaker	byte
	NominalPrice		[7]byte
	X_NominalPrice		byte
	PrevPriceTitle		[12]byte
	X_PrevPriceTitle	byte
	PrevPrice		[7]byte
	X_PrevPrice		byte
	MortgageValue		[7]byte
	X_MortgageValue		byte
	PublicOfferPrice	[7]byte
	X_PublicOfferPrice	byte
	High5Day		[7]byte
	X_High5Day		byte
	Low5Day			[7]byte
	X_Low5Day		byte
	High20Day		[7]byte
	X_High20Day		byte
	Low20Day		[7]byte
	X_Low20Day		byte
	High1Year		[7]byte
	X_High1Year		byte
	High1YearDate		[4]byte
	X_High1YearDate		byte
	Low1Year		[7]byte
	X_Low1Year		byte
	Low1YearDate		[4]byte
	X_Low1YearDate		byte
	FloatVolume		[8]byte
	X_FloatVolume		byte
	ListVolBy1000		[12]byte
	X_ListVolBy1000		byte
	MarketCapital		[9]byte
	X_MarketCapital		byte
	TraderInfoTime		[5]byte
	X_TraderInfoTime	byte
	Seller1			[6]byte
	X_Seller1		byte
	Buyer1			[6]byte
	X_Buyer1		byte
	Seller1Volume		[9]byte
	X_Seller1Volume		byte
	Buyer1Volume		[9]byte
	X_Buyer1Volume		byte
	Seller2			[6]byte
	X_Seller2		byte
	Buyer2			[6]byte
	X_Buyer2		byte
	Seller2Volume		[9]byte
	X_Seller2Volume		byte
	Buyer2Volume		[9]byte
	X_Buyer2Volume		byte
	Seller3			[6]byte
	X_Seller3		byte
	Buyer3			[6]byte
	X_Buyer3		byte
	Seller3Volume		[9]byte
	X_Seller3Volume		byte
	Buyer3Volume		[9]byte
	X_Buyer3Volume		byte
	Seller4			[6]byte
	X_Seller4		byte
	Buyer4			[6]byte
	X_Buyer4		byte
	Seller4Volume		[9]byte
	X_Seller4Volume		byte
	Buyer4Volume		[9]byte
	X_Buyer4Volume		byte
	Seller5			[6]byte
	X_Seller5		byte
	Buyer5			[6]byte
	X_Buyer5		byte
	Seller5Volume		[9]byte
	X_Seller5Volume		byte
	Buyer5Volume		[9]byte
	X_Buyer5Volume		byte
	ForeignSellVolume	[9]byte
	X_ForeignSellVolume	byte
	ForeignBuyVolume	[9]byte
	X_ForeignBuyVolume	byte
	ForeignTime		[6]byte
	X_ForeignTime		byte
	ForeignHoldingRate	[5]byte
	X_ForeignHoldingRate	byte
	SettleDate		[4]byte
	X_SettleDate		byte
	DebtPercent		[5]byte
	X_DebtPercent		byte
	RightsIssueDate		[4]byte
	X_RightsIssueDate	byte
	BonusIssueDate		[4]byte
	X_BonusIssueDate	byte
	RightsIssueRate		[5]byte
	X_RightsIssueRate	byte
	BonusIssueRate		[5]byte
	X_BonusIssueRate	byte
	IpoDate			[8]byte
	X_IpoDate		byte
	ListedVolume		[12]byte
	X_ListedVolume		byte
	SellTotalSum		[9]byte
	X_SellTotalSum		byte
	BuyTotalSum		[9]byte
	X_BuyTotalSum		byte
}
type Tc1151OutBlock2 struct {
	Time		[8]byte
	X_Time		byte
	MarketPrice	[7]byte
	X_MarketPrice	byte
	DiffSign	[1]byte
	X_DiffSign	byte
	Diff		[6]byte
	X_Diff		byte
	OfferPrice	[7]byte
	X_OfferPrice	byte
	BidPrice	[7]byte
	X_BidPrice	byte
	DiffVolume	[8]byte
	X_DiffVolume	byte
	Volume		[9]byte
	X_Volume	byte
}
type Tc1151OutBlock3 struct {
	SyncOfferBid	[1]byte
	X_SyncOfferBid	byte
	EstmPrice	[7]byte
	X_EstmPrice	byte
	EstmSign	[1]byte
	X_EstmSign	byte
	EstmDiff	[6]byte
	X_EstmDiff	byte
	EstmDiffRate	[5]byte
	X_EstmDiffRate	byte
	EstmVolume	[9]byte
	X_EstmVolume	byte
}
type Tc1151OutBlock4 struct {
	ETF			[1]byte
	X_ETF			byte
	NAV			[9]byte
	X_NAV			byte
	DiffSign		[1]byte
	X_DiffSign		byte
	Diff			[9]byte
	X_Diff			byte
	PrevNAV			[9]byte
	X_PrevNAV		byte
	DivergeRate		[9]byte
	X_DivergeRate		byte
	DivergeSign		[1]byte
	X_DivergeSign		byte
	DividendPerCU		[18]byte
	X_DividendPerCU		byte
	ConstituentNo		[4]byte
	X_ConstituentNo		byte
	NAVBy100Million		[7]byte
	X_NAVBy100Million	byte
	TrackingErrRate		[9]byte
	X_TrackingErrRate	byte
	LP_OfferVolume1		[9]byte
	X_LP_OfferVolume1	byte
	LP_OfferVolume2		[9]byte
	X_LP_OfferVolume2	byte
	LP_OfferVolume3		[9]byte
	X_LP_OfferVolume3	byte
	LP_OfferVolume4		[9]byte
	X_LP_OfferVolume4	byte
	LP_OfferVolume5		[9]byte
	X_LP_OfferVolume5	byte
	LP_OfferVolume6		[9]byte
	X_LP_OfferVolume6	byte
	LP_OfferVolume7		[9]byte
	X_LP_OfferVolume7	byte
	LP_OfferVolume8		[9]byte
	X_LP_OfferVolume8	byte
	LP_OfferVolume9		[9]byte
	X_LP_OfferVolume9	byte
	LP_OfferVolume10	[9]byte
	X_LP_OfferVolume10	byte
	LP_BidVolume1		[9]byte
	X_LP_BidVolume1		byte
	LP_BidVolume2		[9]byte
	X_LP_BidVolume2		byte
	LP_BidVolume3		[9]byte
	X_LP_BidVolume3		byte
	LP_BidVolume4		[9]byte
	X_LP_BidVolume4		byte
	LP_BidVolume5		[9]byte
	X_LP_BidVolume5		byte
	LP_BidVolume6		[9]byte
	X_LP_BidVolume6		byte
	LP_BidVolume7		[9]byte
	X_LP_BidVolume7		byte
	LP_BidVolume8		[9]byte
	X_LP_BidVolume8		byte
	LP_BidVolume9		[9]byte
	X_LP_BidVolume9		byte
	LP_BidVolume10		[9]byte
	X_LP_BidVolume10	byte
	TrackingMethod		[8]byte
	X_TrackingMethod	byte
	ETF_Type		[6]byte
	X_ETF_Type		byte
}
type Tc1151OutBlock5 struct {
	IndexCode		[2]byte
	X_IndexCode		byte
	SectorCode		[4]byte
	X_SectorCode		byte
	IndexName		[20]byte
	X_IndexName		byte
	KP200Index		[8]byte
	X_KP200Index		byte
	KP200Sign		[1]byte
	X_KP200Sign		byte
	KP200Diff		[8]byte
	X_KP200Diff		byte
	BondIndex		[10]byte
	X_BondIndex		byte
	BondSign		[1]byte
	X_BondSign		byte
	BondDiff		[10]byte
	X_BondDiff		byte
	ForeignIndexSymbol	[12]byte
	X_ForeignIndexSymbol	byte
	EtcSectorCode		[3]byte
	X_EtcSectorCode		byte
	BondIndexCode		[6]byte
	X_BondIndexCode		byte
	BondDetailCode		[1]byte
	X_BondDetailCode	byte
}

type Th1InBlock struct {
	Code [6]byte
}
type Th1OutBlock struct {
	Code		[6]byte
	Time		[8]byte
	OfferPrice1	[7]byte
	BidPrice1	[7]byte
	OfferVolume1	[9]byte
	BidVolume1	[9]byte
	OfferPrice2	[7]byte
	BidPrice2	[7]byte
	OfferVolume2	[9]byte
	BidVolume2	[9]byte
	OfferPrice3	[7]byte
	BidPrice3	[7]byte
	OfferVolume3	[9]byte
	BidVolume3	[9]byte
	OfferPrice4	[7]byte
	BidPrice4	[7]byte
	OfferVolume4	[9]byte
	BidVolume4	[9]byte
	OfferPrice5	[7]byte
	BidPrice5	[7]byte
	OfferVolume5	[9]byte
	BidVolume5	[9]byte
	OfferPrice6	[7]byte
	BidPrice6	[7]byte
	OfferVolume6	[9]byte
	BidVolume6	[9]byte
	OfferPrice7	[7]byte
	BidPrice7	[7]byte
	OfferVolume7	[9]byte
	BidVolume7	[9]byte
	OfferPrice8	[7]byte
	BidPrice8	[7]byte
	OfferVolume8	[9]byte
	BidVolume8	[9]byte
	OfferPrice9	[7]byte
	BidPrice9	[7]byte
	OfferVolume9	[9]byte
	BidVolume9	[9]byte
	OfferPrice10	[7]byte
	BidPrice10	[7]byte
	OfferVolume10	[9]byte
	BidVolume10	[9]byte
	Volume		[9]byte
}

type Tk3InBlock struct {
	Code [6]byte
}
type Tk3OutBlock struct {
	Code		[6]byte
	Time		[8]byte
	OfferPrice1	[7]byte
	BidPrice1	[7]byte
	OfferVolume1	[9]byte
	BidVolume1	[9]byte
	OfferPrice2	[7]byte
	BidPrice2	[7]byte
	OfferVolume2	[9]byte
	BidVolume2	[9]byte
	OfferPrice3	[7]byte
	BidPrice3	[7]byte
	OfferVolume3	[9]byte
	BidVolume3	[9]byte
	OfferPrice4	[7]byte
	BidPrice4	[7]byte
	OfferVolume4	[9]byte
	BidVolume4	[9]byte
	OfferPrice5	[7]byte
	BidPrice5	[7]byte
	OfferVolume5	[9]byte
	BidVolume5	[9]byte
	OfferPrice6	[7]byte
	BidPrice6	[7]byte
	OfferVolume6	[9]byte
	BidVolume6	[9]byte
	OfferPrice7	[7]byte
	BidPrice7	[7]byte
	OfferVolume7	[9]byte
	BidVolume7	[9]byte
	OfferPrice8	[7]byte
	BidPrice8	[7]byte
	OfferVolume8	[9]byte
	BidVolume8	[9]byte
	OfferPrice9	[7]byte
	BidPrice9	[7]byte
	OfferVolume9	[9]byte
	BidVolume9	[9]byte
	OfferPrice10	[7]byte
	BidPrice10	[7]byte
	OfferVolume10	[9]byte
	BidVolume10	[9]byte
	Volume		[9]byte
}

type Th2InBlock struct {
	Code [6]byte
}
type Th2OutBlock struct {
	Code		[6]byte
	Time		[8]byte
	OfferVolume	[9]byte
	BidVolume	[9]byte
}

type Tk4InBlock struct {
	Code [6]byte
}
type Tk4OutBlock struct {
	Code		[6]byte
	Time		[8]byte
	OfferVolume	[9]byte
	BidVolume	[9]byte
}

type Th3InBlock struct {
	Code [6]byte
}
type Th3OutBlock struct {
	Code		[6]byte
	Time		[8]byte
	SyncOfferBid	[1]byte
	EstmPrice	[7]byte
	EstmDiffSign	[1]byte
	EstmDiff	[6]byte
	EstmDiffRate	[5]byte
	EstmVolume	[9]byte
	OfferPrice	[7]byte
	BidPrice	[7]byte
	OfferVolume	[9]byte
	BidVolume	[9]byte
}

type Tk5InBlock struct {
	Code [6]byte
}
type Tk5OutBlock struct {
	Code		[6]byte
	Time		[8]byte
	SyncOfferBid	[1]byte
	EstmPrice	[7]byte
	EstmDiffSign	[1]byte
	EstmDiff	[6]byte
	EstmDiffRate	[5]byte
	EstmVolume	[9]byte
	OfferPrice	[7]byte
	BidPrice	[7]byte
	OfferVolume	[9]byte
	BidVolume	[9]byte
}

type Tj8InBlock struct {
	Code	[6]byte
	X_Code	byte
}
type Tj8OutBlock struct {
	Code			[6]byte
	X_Code			byte
	Time			[8]byte
	X_Time			byte
	DiffSign		[1]byte
	X_DiffSign		byte
	Diff			[6]byte
	X_Diff			byte
	MarketPrice		[7]byte
	X_MarketPrice		byte
	DiffRate		[5]byte
	X_DiffRate		byte
	High			[7]byte
	X_High			byte
	Low			[7]byte
	X_Low			byte
	OfferPrice		[7]byte
	X_OfferPrice		byte
	BidPrice		[7]byte
	X_BidPrice		byte
	Volume			[9]byte
	X_Volume		byte
	VsPrevVolRate		[6]byte
	X_VsPrevVolRate		byte
	DiffVolume		[8]byte
	X_DiffVolume		byte
	TrAmount		[9]byte
	X_TrAmount		byte
	Open			[7]byte
	X_Open			byte
	WeightAvgPrice		[7]byte
	X_WeightAvgPrice	byte
	Market			[1]byte
	X_Market		byte
}

type Tk8InBlock struct {
	Code	[6]byte
	X_Code	byte
}
type Tk8OutBlock struct {
	Code			[6]byte
	X_Code			byte
	Time			[8]byte
	X_Time			byte
	MarketPrice		[7]byte
	X_MarketPrice		byte
	DiffSign		[1]byte
	X_DiffSign		byte
	Diff			[6]byte
	X_Diff			byte
	DiffRate		[5]byte
	X_DiffRate		byte
	High			[7]byte
	X_High			byte
	Low			[7]byte
	X_Low			byte
	OfferPrice		[7]byte
	X_OfferPrice		byte
	BidPrice		[7]byte
	X_BidPrice		byte
	Volume			[9]byte
	X_Volume		byte
	VolRate			[6]byte
	X_VolRate		byte
	DiffVolume		[8]byte
	X_DiffVolume		byte
	TrAmount		[9]byte
	X_TrAmount		byte
	Open			[7]byte
	X_Open			byte
	WeightAvgPrice		[7]byte
	X_WeightAvgPrice	byte
	Market			[1]byte
	X_Market		byte
}

type Tj1InBlock struct {
	Code	[6]byte
	X_Code	byte
}
type Tj1OutBlock struct {
	Code		[6]byte
	X_Code		byte
	Time		[8]byte
	X_Time		byte
	DiffSign	[1]byte
	X_DiffSign	byte
	Diff		[9]byte
	X_Diff		byte
	Current		[9]byte
	X_NAV_Current	byte
	Open		[9]byte
	X_NAV_Open	byte
	High		[9]byte
	X_NAV_High	byte
	Low		[9]byte
	X_NAV_Low	byte
	TrackErrSign	[1]byte
	X_TrackingSign	byte
	TrackingError	[9]byte
	X_TrackingError	byte
	DivergeSign	[1]byte
	X_DivergeSign	byte
	DivergeRate	[9]byte
	X_DivergeRate	byte
}

type Tj0InBlock struct {
	Code	[6]byte
	X_Code	byte
}
type Tj0OutBlock struct {
	Code		[6]byte
	X_Code		byte
	Time		[8]byte
	X_Time		byte
	DiffSign	[1]byte
	X_DiffSign	byte
	Diff		[9]byte
	X_Diff		byte
	Current		[9]byte
	X_NAV_Current	byte
	Open		[9]byte
	X_NAV_Open	byte
	High		[9]byte
	X_NAV_High	byte
	Low		[9]byte
	X_NAV_Low	byte
	TrackErrSign	[1]byte
	X_TrackErrSign	byte
	TrackingError	[9]byte
	X_TrackingError	byte
	DivergeSign	[1]byte
	X_DivergeSign	byte
	DivergeRate	[9]byte
	X_DivergeRate	byte
}

type Tu1InBlock struct {
	SectorCode	[2]byte
	X_SectorCode	byte
}
type Tu1OutBlock struct {
	SectorCode	[2]byte
	X_SectorCode	byte
	Time		[8]byte
	X_Time		byte
	IndexValue	[8]byte
	X_IndexValue	byte
	DiffSign	[1]byte
	X_DiffSign	byte
	Diff		[8]byte
	X_Diff		byte
	Volume		[8]byte
	X_Volume	byte
	TrAmount	[8]byte
	X_TrAmount	byte
	Open		[8]byte
	X_Open		byte
	High		[8]byte
	X_High		byte
	HighTime	[8]byte
	X_HighTime	byte
	Low		[8]byte
	X_Low		byte
	LowTime		[8]byte
	X_LowTime	byte
	DiffRate	[5]byte
	X_DiffRate	byte
	TrVolRate	[5]byte
	X_TrVolRate	byte
}

type Tk1InBlock struct {
	SectorCode	[2]byte
	X_SectorCode	byte
}
type Tk1OutBlock struct {
	SectorCode	[2]byte
	X_SectorCode	byte
	Time		[8]byte
	X_Time		byte
	IndexValue	[8]byte
	X_IndexValue	byte
	DiffSign	[1]byte
	X_DiffSign	byte
	Diff		[8]byte
	X_Diff		byte
	Volume		[8]byte
	X_Volume	byte
	TrAmount	[8]byte
	X_TrAmount	byte
	Open		[8]byte
	X_Open		byte
	High		[8]byte
	X_High		byte
	HighTime	[8]byte
	X_HighTime	byte
	Low		[8]byte
	X_Low		byte
	LowTime		[8]byte
	X_LowTime	byte
	DiffRate	[5]byte
	X_DiffRate	byte
	TrVolRate	[5]byte
	X_TrVolRate	byte
}
