#ifndef CONSTWINMSG_HPP
#define CONSTWINMSG_HPP

#define KM_INIT WM_USER+100
#define KM_CONNECT KM_INIT+1
#define KM_LOGIN_INFO KM_INIT+4

#define KM_PRINT_DEBUG_MSG KM_INIT + 300

#endif // CONSTWINMSG_HPP
